package net.rim.device.apps.internal.addressbook.lookup;

interface ALPConstants {
   long ALP_LOGGER_GUID;
   long ALP_CONFIGURATION;
   String ALP_SERVICE_CID;
   String ALP_EVENT_LOGGER_NAME;
   String RIM_ALP_REQUEST;
   String RIM_ALP_RESULT;
   int ALP_MAJOR_VERSION;
   int ALP_MINOR_VERSION;
   int ALP_CURRENT_VERSION;
   int ALP_ACTION_SEARCH;
   int ALP_ACTION_RESULT;
   int ALP_ACTION_TEMPORARY_ERROR;
   int ALP_ACTION_PERMANENT_ERROR;
   int ALP_FIELD_LOOKUP_RESULT;
   int ALP_FIELD_SEARCH_STRING;
   int ALP_FIELD_INCLUDED_MATCHES;
   int ALP_FIELD_AVAILABLE_MATCHES;
   int ALP_FIELD_OFFSET;
   int ALP_FIELD_DESIRED_MATCHES;
   int ALP_FIELD_DESIRED_FIELDS;
   int ALP_FIELD_MATCH_SORT_ORDER;
   int ALP_FIELD_ERROR_STRING;
   int ALP_FIELD_ERROR_CODE;
   int ALP_FIELD_END_OF_FIELDS;
   int ALP_FIELD_SEARCH_STRING_2;
   int ALP_ERROR_UNKNOWN;
}
