package net.rim.device.cldc.io.commlink;

interface Constants {
   int DEFAULT_BAUD_RATE = 9600;
   int MAX_BAUD_RATE = 115200;
   int MIN_MTU_SIZE = 128;
   int MAX_DATA_SIZE = 1024;
   int OVERHEAD_SIZE = 12;
   int TX_BUFFER_SIZE = 1036;
   int RX_BUFFER_SIZE = 1036;
   int CHALLENGE_DATA_SIZE = 20;
   int MAX_RESPONSE_DATA_SIZE = 33;
   int MAX_RETRIES = 3;
   int SC_ID = 0;
   int TIME_OUT = 3000;
   int AFTER_BAUD_CHANGE_TIMEOUT = 1000;
   int WAKEUP_TIMEOUT = 1000;
   int SC_DATA_OFFSET = 7;
   byte ACK = 6;
   byte NAK = 21;
   byte HEADER0 = -39;
   byte HEADER1 = -82;
   byte HEADER2 = -5;
   byte[] HEADER;
   byte TRAILER0 = -65;
   byte TRAILER1 = -22;
   byte TRAILER2 = -99;
   byte HELLO_REQ = -49;
   byte HELLO_ACK = -50;
   byte NEW_HELLO_ACK = -63;
   byte DESKTOP_VERSION = 15;
   byte[] NOTIFY_PATTERN;
   byte DATA_PACKET = 64;
   byte REPLY_PACKET = 65;
   byte MORE_FLAG = 32;
   byte PACKET_TYPE_MASK = 67;
   byte SC_IDLE_CMD = 1;
   byte NO_PASSWORD = 0;
   byte SHA_1 = 1;
   byte LAST_ATTEMPT = -128;
   byte SC_MAJOR = 2;
   byte SC_MINOR = 0;
   byte OPTIONS_VER_MINOR = 0;
   byte OPTIONS_VER_MAJOR = 4;
   byte CHALLENGE_NONE = -1;
   byte CHALLENGE_DEVICE = 0;
   byte CHALLENGE_DESKTOP = 1;
   byte CHALLENGE_DESKTOP_CHAP = 2;
   byte CHALLENGE_DEVICE_FORCED = 16;
   byte CHALLENGE_DESKTOP_FORCED = 17;
   byte CHALLENGE_DESKTOP_CHAP_FORCED = 18;
   byte[] PASSWORD_TYPE;
   int VERSION = 131076;
   int REPLY_OK = 0;
   int LINK_ERROR = 32768;
   int LINK_CONNECTED = 32769;
   int LINK_DISCONNECTED = 32770;
   int LINK_TIMEOUT_ERROR = 32771;
   int LINK_COMM_ERROR = 32772;
   int ID_UNKNOWN = 32773;
   int INVALID_PASSWORD = 32774;
   int NO_ERROR = 0;
   int APP_ERROR = 40960;
   int WAITING_FOR_LOGIN = 1;
   int WAITING_FOR_CHALLENGE_RESPONSE = 2;
   int WAITING_FOR_APP_DATA = 3;
}
