package net.rim.device.internal.crypto.vpn;

import net.rim.device.api.system.RadioListener;

public interface VPNListener extends RadioListener {
   int VPN_CONNECT = 8960;
   int VPN_DISCONNECT = 8961;
   int VPN_CONNECTED = 8962;
   int VPN_DISCONNECTED = 8966;
   int VPN_STATUS_ERROR = -2;
   int VPN_STATUS_OK = 0;
   int VPN_STATUS_ERROR_INVALID_HANDLE_ID = -27;
   int VPN_STATUS_ERROR_BAD_CERT_VALIDITY_PERIOD = -26;
   int VPN_STATUS_ERROR_TIMEOUT = -25;
   int VPN_STATUS_ERROR_EAPAKA_FAILED = -24;
   int VPN_STATUS_ERROR_EAPSIM_FAILED = -23;
   int VPN_STATUS_ERROR_NO_SIM_CHALLENGE = -21;
   int VPN_STATUS_DISCONNECTED_BY_GATEWAY = -20;
   int VPN_STATUS_ERROR_PASSWORD_REQUIRED = -17;
   int VPN_STATUS_ERROR_USERNAME_REQUIRED = -16;
   int VPN_STATUS_ERROR_GROUPPASSWORD_REQUIRED = -15;
   int VPN_STATUS_ERROR_GROUPNAME_REQUIRED = -14;
   int VPN_STATUS_ERROR_BAD_GATEWAY_TYPE = -13;
   int VPN_STATUS_ERROR_BAD_PSK = -12;
   int VPN_STATUS_ERROR_BAD_GATEWAY_AUTH_ID_TYPE = -11;
   int VPN_STATUS_ERROR_BAD_GATEWAY_AUTH_ID = -10;
   int VPN_STATUS_ERROR_NOT_LOGGED_IN = -7;
   int VPN_STATUS_ABORTED = -1;
   int VPN_STATUS_OK_CONNECTED = 4;
   int VPN_STATUS_OK_DISCONNECTED = 5;
   int VPN_STATUS_OK_SIM_CHALLENGE = 8;
   int VPN_STATUS_OK_AKA_CHALLENGE = 9;
   int VPN_STATUS_OK_RESOLVE_GATEWAY = 11;
   int VPN_STATUS_OK_PROMPT_USER = 12;
   int VPN_STATUS_OK_CHECK_CERTIFICATE = 13;

   void vpnStatusChanged(int var1, int var2, int var3, int var4);
}
