package net.rim.device.internal.crypto.vpn;

import net.rim.device.api.system.RadioListener;

public interface VPNListener extends RadioListener {
   int VPN_CONNECT;
   int VPN_DISCONNECT;
   int VPN_CONNECTED;
   int VPN_DISCONNECTED;
   int VPN_STATUS_ERROR;
   int VPN_STATUS_OK;
   int VPN_STATUS_ERROR_INVALID_HANDLE_ID;
   int VPN_STATUS_ERROR_BAD_CERT_VALIDITY_PERIOD;
   int VPN_STATUS_ERROR_TIMEOUT;
   int VPN_STATUS_ERROR_EAPAKA_FAILED;
   int VPN_STATUS_ERROR_EAPSIM_FAILED;
   int VPN_STATUS_ERROR_NO_SIM_CHALLENGE;
   int VPN_STATUS_DISCONNECTED_BY_GATEWAY;
   int VPN_STATUS_ERROR_PASSWORD_REQUIRED;
   int VPN_STATUS_ERROR_USERNAME_REQUIRED;
   int VPN_STATUS_ERROR_GROUPPASSWORD_REQUIRED;
   int VPN_STATUS_ERROR_GROUPNAME_REQUIRED;
   int VPN_STATUS_ERROR_BAD_GATEWAY_TYPE;
   int VPN_STATUS_ERROR_BAD_PSK;
   int VPN_STATUS_ERROR_BAD_GATEWAY_AUTH_ID_TYPE;
   int VPN_STATUS_ERROR_BAD_GATEWAY_AUTH_ID;
   int VPN_STATUS_ERROR_NOT_LOGGED_IN;
   int VPN_STATUS_ABORTED;
   int VPN_STATUS_OK_CONNECTED;
   int VPN_STATUS_OK_DISCONNECTED;
   int VPN_STATUS_OK_SIM_CHALLENGE;
   int VPN_STATUS_OK_AKA_CHALLENGE;
   int VPN_STATUS_OK_RESOLVE_GATEWAY;
   int VPN_STATUS_OK_PROMPT_USER;
   int VPN_STATUS_OK_CHECK_CERTIFICATE;

   void vpnStatusChanged(int var1, int var2, int var3, int var4);
}
