package net.rim.plazmic.internal.mediaengine.format;

public interface Constants {
   int TEXT_ATTR_STYLE_NORMAL;
   int TEXT_ATTR_STYLE_ITALIC;
   int TEXT_ATTR_STYLE_OBLIQUE;
   int TEXT_ATTR_DECORATION_NONE;
   int TEXT_ATTR_DECORATION_UNDERLINE;
   int TEXT_ATTR_DECORATION_UNDERLINE_DOTTED;
   int TEXT_ATTR_DECORATION_UNDERLINE_BROKEN_LINE;
   int TEXT_ATTR_DECORATION_LINE_THROUGH;
   int TEXT_ATTR_DECORATION_INHERIT;
   int TEXT_ATTR_WEIGHT_PLAIN;
   int TEXT_ATTR_WEIGHT_BOLD;
   int UNITS_PIXELS;
   int UNITS_POINTS;
   int UNITS_CENTIPOINTS;
   int UNITS_PTD;
   int UNITS_CPTD;
   int UNITS_METRES;
   int UNITS_CENTIMETRES;
   int UNITS_MILLIMETRES;
   int UNITS_MICROMETRES;
   int UNITS_PICOMETRES;
   int BEZIER_END_POINT;
   int BEZIER_QUADRATIC_CONTROL_POINT;
   int BEZIER_CUBIC_CONTROL_POINT;
   int HINT_AUTO;
   int HINT_OPTIMIZE_SPEED;
   int HINT_GEOMETRIC_PRECISION;
   int HINT_IMAGE_OPTIMIZE_QUALITY;
   int HINT_TEXT_OPTIMIZE_LEGIBILITY;
   int HINT_SHAPE_CRISP_EDGES;
   int HINTS_HAS_IMAGE_HINT;
   int HINTS_HAS_TEXT_HINT;
   int HINTS_HAS_SHAPE_HINT;
}
