package net.rim.plazmic.internal.mediaengine.format;

public interface Constants {
   int TEXT_ATTR_STYLE_NORMAL = 1;
   int TEXT_ATTR_STYLE_ITALIC = 2;
   int TEXT_ATTR_STYLE_OBLIQUE = 3;
   int TEXT_ATTR_DECORATION_NONE = 1;
   int TEXT_ATTR_DECORATION_UNDERLINE = 2;
   int TEXT_ATTR_DECORATION_UNDERLINE_DOTTED = 3;
   int TEXT_ATTR_DECORATION_UNDERLINE_BROKEN_LINE = 4;
   int TEXT_ATTR_DECORATION_LINE_THROUGH = 5;
   int TEXT_ATTR_DECORATION_INHERIT = 6;
   int TEXT_ATTR_WEIGHT_PLAIN = 1;
   int TEXT_ATTR_WEIGHT_BOLD = 2;
   int UNITS_PIXELS = 0;
   int UNITS_POINTS = 1;
   int UNITS_CENTIPOINTS = 2;
   int UNITS_PTD = 3;
   int UNITS_CPTD = 4;
   int UNITS_METRES = 5;
   int UNITS_CENTIMETRES = 6;
   int UNITS_MILLIMETRES = 7;
   int UNITS_MICROMETRES = 8;
   int UNITS_PICOMETRES = 9;
   int BEZIER_END_POINT = 0;
   int BEZIER_QUADRATIC_CONTROL_POINT = 1;
   int BEZIER_CUBIC_CONTROL_POINT = 2;
   int HINT_AUTO = 0;
   int HINT_OPTIMIZE_SPEED = 1;
   int HINT_GEOMETRIC_PRECISION = 2;
   int HINT_IMAGE_OPTIMIZE_QUALITY = 3;
   int HINT_TEXT_OPTIMIZE_LEGIBILITY = 3;
   int HINT_SHAPE_CRISP_EDGES = 3;
   int HINTS_HAS_IMAGE_HINT = 1;
   int HINTS_HAS_TEXT_HINT = 2;
   int HINTS_HAS_SHAPE_HINT = 4;
}
