package net.rim.device.internal.provisioning;

public final class ProvisioningConstants {
   public static final int ENABLE_ENTERPRISE_ACTIVATE_UI_TYPE = 1;
   public static final int BB_EXP_MODE_TYPE = 2;
   public static final int IP_MODEM_TYPE = 3;
   public static final int MORE_IMAGES_URL_TYPE = 4;
   public static final int MORE_TUNES_URL_TYPE = 5;
   public static final int MORE_THEMES_URL_TYPE = 6;
   public static final int MDP_STACK_FLAG = 7;
   public static final int WLAN_PROFILES_TYPE = 8;
   public static final int GAN_SECURE_GATEWAY = 9;
   public static final int GAN_CONTROLLER = 10;
   public static final int GAN_ROOT_CERT_1 = 11;
   public static final int GAN_ROOT_CERT_2 = 12;
   public static final int GAN_ROOT_CERT_3 = 13;
   public static final int GAN_ROOT_CERT_4 = 14;
   public static final int ENABLE_WLAN = 15;
   public static final int ENABLE_GAN_PREFERENCE_WAN_ONLY = 16;
   public static final int ENABLE_GAN_PREFERENCE_WAN_PREFERRED = 17;
   public static final int ENABLE_GAN_PREFERENCE_GAN_ONLY = 18;
   public static final int ENABLE_GAN_PREFERENCE_GAN_PREFERRED = 19;
   public static final int SUPL_SERVER_ADDRESS = 20;
   public static final int GAN_WLAN_THRESHOLD = 21;
   public static final int GAN_SIGNAL_STRENGTH_THRESHOLD = 22;
   public static final int GAN_SIGNAL_QUALITY_THRESHOLD = 23;
   public static final int DTM_VERSION = 24;
   public static final int RRLP_VERSION = 25;
   public static final int SUPL_VERSION = 26;
   public static final int INTERACTIVE_PACKET_PING_TIMEOUT = 27;
   public static final int GAN_CERT_THUMBPRINT = 28;
   public static final int ENABLE_WLAN_ACCESS_TO_BLACKBERRY_ROUTER = 29;
   public static final int ENABLE_WLAN_ACCESS_TO_RELAY = 30;
   public static final int DISABLE_EXTENDED_EPHEMERIS = 32;
   public static final int GAN_PROTOCOL_VERSION = 33;
   public static final int GAN_PROTOCOL_VERSION_UMA_1_0_0 = 0;
   public static final int GAN_PROTOCOL_VERSION_UMA_1_0_1 = 1;
   public static final int GAN_PROTOCOL_VERSION_UMA_1_0_2 = 2;
   public static final int GAN_PROTOCOL_VERSION_UMA_1_0_3 = 3;
   public static final int GAN_PROTOCOL_VERSION_UMA_1_0_4 = 4;
   public static final int GAN_PROTOCOL_VERSION_3GPP_rev6 = 5;
   public static final int DISABLE_BLACKBERRY_PROTECTED_MODE = 34;
   public static final int SUPL_APN = 35;
   public static final int SUPL_APN_USERNAME = 36;
   public static final int SUPL_APN_PASSWORD = 37;
   public static final int ENABLE_QUICK_CONNECT = 38;
}
