package net.rim.ecmascript.runtime;

import java.util.Hashtable;
import net.rim.ecmascript.util.Misc;

public class Names {
   public static final String __proto__;
   public static final String _boolean;
   public static final String _false;
   public static final String _null;
   public static final String _true;
   public static final String abs;
   public static final String acos;
   public static final String activation;
   public static final String apply;
   public static final String arguments;
   public static final String Arguments;
   public static final String arity;
   public static final String Array;
   public static final String asin;
   public static final String atan;
   public static final String atan2;
   public static final String Boolean;
   public static final String call;
   public static final String callee;
   public static final String ceil;
   public static final String charAt;
   public static final String charCodeAt;
   public static final String compile;
   public static final String concat;
   public static final String constructor;
   public static final String cos;
   public static final String Date;
   public static final String decodeURI;
   public static final String decodeURIComponent;
   public static final String E;
   public static final String encodeURI;
   public static final String encodeURIComponent;
   public static final String Error;
   public static final String escape;
   public static final String eval;
   public static final String EvalError;
   public static final String exec;
   public static final String exp;
   public static final String floor;
   public static final String fromCharCode;
   public static final String Function;
   public static final String function;
   public static final String getDate;
   public static final String getDay;
   public static final String getFullYear;
   public static final String getHours;
   public static final String getMilliseconds;
   public static final String getMinutes;
   public static final String getMonth;
   public static final String getSeconds;
   public static final String getTime;
   public static final String getTimezoneOffset;
   public static final String getUTCDate;
   public static final String getUTCDay;
   public static final String getUTCFullYear;
   public static final String getUTCHours;
   public static final String getUTCMilliseconds;
   public static final String getUTCMinutes;
   public static final String getUTCMonth;
   public static final String getUTCSeconds;
   public static final String getYear;
   public static final String global;
   public static final String hasOwnProperty;
   public static final String ignoreCase;
   public static final String importClass;
   public static final String importPackage;
   public static final String index;
   public static final String indexOf;
   public static final String Infinity;
   public static final String input;
   public static final String InternalError;
   public static final String isFinite;
   public static final String isNaN;
   public static final String isPrototypeOf;
   public static final String JavaArray;
   public static final String JavaBooleanArray;
   public static final String JavaByteArray;
   public static final String JavaCharArray;
   public static final String JavaClass;
   public static final String JavaConstructor;
   public static final String JavaDoubleArray;
   public static final String JavaFloatArray;
   public static final String JavaIntArray;
   public static final String JavaInterface;
   public static final String JavaLongArray;
   public static final String JavaMethod;
   public static final String JavaObject;
   public static final String JavaOverloadedConstructor;
   public static final String JavaOverloadedMethod;
   public static final String JavaPackage;
   public static final String JavaShortArray;
   public static final String join;
   public static final String lastIndex;
   public static final String lastIndexOf;
   public static final String lastMatch;
   public static final String lastParen;
   public static final String leftContext;
   public static final String length;
   public static final String LN10;
   public static final String LN2;
   public static final String localeCompare;
   public static final String log;
   public static final String LOG10E;
   public static final String LOG2E;
   public static final String match;
   public static final String Math;
   public static final String max;
   public static final String MAX_VALUE;
   public static final String message;
   public static final String min;
   public static final String MIN_VALUE;
   public static final String multiline;
   public static final String name;
   public static final String NaN;
   public static final String Namespace;
   public static final String namespace;
   public static final String NEGATIVE_INFINITY;
   public static final String number;
   public static final String Number;
   public static final String object;
   public static final String Object;
   public static final String Packages;
   public static final String parse;
   public static final String parseFloat;
   public static final String parseInt;
   public static final String PI;
   public static final String pop;
   public static final String POSITIVE_INFINITY;
   public static final String pow;
   public static final String prefix;
   public static final String print;
   public static final String propertyIsEnumerable;
   public static final String prototype;
   public static final String push;
   public static final String quit;
   public static final String random;
   public static final String RangeError;
   public static final String ReferenceError;
   public static final String RegExp;
   public static final String replace;
   public static final String reverse;
   public static final String rightContext;
   public static final String round;
   public static final String search;
   public static final String setDate;
   public static final String setFullYear;
   public static final String setHours;
   public static final String setMilliseconds;
   public static final String setMinutes;
   public static final String setMonth;
   public static final String setSeconds;
   public static final String setTime;
   public static final String setUTCDate;
   public static final String setUTCFullYear;
   public static final String setUTCHours;
   public static final String setUTCMilliseconds;
   public static final String setUTCMinutes;
   public static final String setUTCMonth;
   public static final String setUTCSeconds;
   public static final String setYear;
   public static final String shift;
   public static final String sin;
   public static final String slice;
   public static final String sort;
   public static final String source;
   public static final String splice;
   public static final String split;
   public static final String sqrt;
   public static final String SQRT1_2;
   public static final String SQRT2;
   public static final String string;
   public static final String String;
   public static final String substr;
   public static final String substring;
   public static final String SyntaxError;
   public static final String tan;
   public static final String test;
   public static final String toDateString;
   public static final String toExponential;
   public static final String toFixed;
   public static final String toGMTString;
   public static final String toLocaleDateString;
   public static final String toLocaleLowerCase;
   public static final String toLocaleString;
   public static final String toLocaleTimeString;
   public static final String toLocaleUpperCase;
   public static final String toLowerCase;
   public static final String toPrecision;
   public static final String toString;
   public static final String toTimeString;
   public static final String toUpperCase;
   public static final String toUTCString;
   public static final String TypeError;
   public static final String undefined;
   public static final String unescape;
   public static final String unshift;
   public static final String URIError;
   public static final String uri;
   public static final String UTC;
   public static final String valueOf;
   public static final String version;
   public static final Hashtable constructors = (Hashtable)(new Object());
   public static final long[] NoParms = Misc.newMixedArray(0);

   private Names() {
   }

   static {
      constructors.put("Array", "Array");
      constructors.put("Boolean", "Boolean");
      constructors.put("Date", "Date");
      constructors.put("Error", "Error");
      constructors.put("EvalError", "EvalError");
      constructors.put("Function", "Function");
      constructors.put("Number", "Number");
      constructors.put("Object", "Object");
      constructors.put("RangeError", "RangeError");
      constructors.put("ReferenceError", "ReferenceError");
      constructors.put("RegExp", "RegExp");
      constructors.put("String", "String");
      constructors.put("SyntaxError", "SyntaxError");
      constructors.put("TypeError", "TypeError");
      constructors.put("URIError", "URIError");
   }
}
