package net.rim.device.apps.internal.secureemail.encodings.smime;

public interface SMIMEConstants {
   String CONTENTTYPE_MULTIPART_SIGNED;
   String CONTENTTYPE_APPLICATION_XPKCS7MIME;
   String CONTENTTYPE_APPLICATION_PKCS7MIME;
   String SECURITY_ENCODING_SMIME;
   byte[] SECURITY_ENCODING_SMIME_BYTES;
   String ENHANCED_CONTENT_TYPE_SMIME;
   String SECURITY_ENCODING_SMIME_NOVERIFY_TOOLONG;
   byte[] SECURITY_ENCODING_SMIME_NOVERIFY_TOOLONG_BYTES;
   String ENHANCED_CONTENT_TYPE_SMIME_NOVERIFY_TOOLONG;
   String SECURITY_ENCODING_SMIME_NOVERIFY_NOATTACH;
   byte[] SECURITY_ENCODING_SMIME_NOVERIFY_NOATTACH_BYTES;
   String ENHANCED_CONTENT_TYPE_SMIME_NOVERIFY_NOATTACH;
   long PER_MESSAGE_OPTIONS;
   long EVENT_LOGGER_GUID;
   boolean INCLUDE_CERTS_PIN_DEFAULT;
   boolean INCLUDE_CERTS_EMAIL_DEFAULT;
   int MAX_NUM_SIGNED_RECEIPTS_TO_CACHE;
   int DEFAULT_RECIPIENT_CONTENT_CIPHERS;
   int SUPPORTED_RECIPIENT_CONTENT_CIPHERS;
}
