package net.rim.device.apps.internal.secureemail.encodings.smime;

public interface SMIMEAppPolicy {
   int SMIME_REQUIRE_FIPS_CIPHERS = 1;
   int SMIME_DISABLE_WEAK_CIPHERS = 2;
   int SMIME_MIN_STRONG_RSA_KEY_LENGTH = 3;
   int SMIME_MIN_STRONG_DH_KEY_LENGTH = 4;
   int SMIME_MIN_STRONG_ECC_KEY_LENGTH = 5;
   int FORCE_SMIME_DIGITAL_SIGNATURE = 6;
   int FORCE_SMIME_ENCRYPTED_EMAIL = 7;
   int FORCE_SMIME_SMARTCARD_USE = 8;
   int SMIME_BCC_ADDRESS = 9;
   int SMIME_ALLOWED_CONTENT_CIPHERS = 10;
   int SMIME_MIN_STRONG_DSA_KEY_LENGTH = 11;
   int SMIME_EMS_EMAIL_ADDRESS = 12;
   int SMIME_MIN_STRONG_RSA_KEY_LENGTH_DEFAULT = 1024;
   int SMIME_MIN_STRONG_DH_KEY_LENGTH_DEFAULT = 1024;
   int SMIME_MIN_STRONG_ECC_KEY_LENGTH_DEFAULT = 163;
   boolean FORCE_SMIME_DIGITAL_SIGNATURE_DEFAULT = false;
   boolean FORCE_SMIME_ENCRYPTED_EMAIL_DEFAULT = false;
   boolean FORCE_SMIME_SMARTCARD_USE_DEFAULT = false;
   int SMIME_ALLOWED_CONTENT_CIPHERS_DEFAULT = 63;
   int SMIME_MIN_STRONG_DSA_KEY_LENGTH_DEFAULT = 1024;
}
