package net.rim.device.apps.internal.secureemail.encodings.smime;

public interface SMIMEAppPolicy {
   int SMIME_REQUIRE_FIPS_CIPHERS;
   int SMIME_DISABLE_WEAK_CIPHERS;
   int SMIME_MIN_STRONG_RSA_KEY_LENGTH;
   int SMIME_MIN_STRONG_DH_KEY_LENGTH;
   int SMIME_MIN_STRONG_ECC_KEY_LENGTH;
   int FORCE_SMIME_DIGITAL_SIGNATURE;
   int FORCE_SMIME_ENCRYPTED_EMAIL;
   int FORCE_SMIME_SMARTCARD_USE;
   int SMIME_BCC_ADDRESS;
   int SMIME_ALLOWED_CONTENT_CIPHERS;
   int SMIME_MIN_STRONG_DSA_KEY_LENGTH;
   int SMIME_EMS_EMAIL_ADDRESS;
   int SMIME_MIN_STRONG_RSA_KEY_LENGTH_DEFAULT;
   int SMIME_MIN_STRONG_DH_KEY_LENGTH_DEFAULT;
   int SMIME_MIN_STRONG_ECC_KEY_LENGTH_DEFAULT;
   boolean FORCE_SMIME_DIGITAL_SIGNATURE_DEFAULT;
   boolean FORCE_SMIME_ENCRYPTED_EMAIL_DEFAULT;
   boolean FORCE_SMIME_SMARTCARD_USE_DEFAULT;
   int SMIME_ALLOWED_CONTENT_CIPHERS_DEFAULT;
   int SMIME_MIN_STRONG_DSA_KEY_LENGTH_DEFAULT;
}
