package net.rim.device.apps.internal.secureemail.encodings.smime;

public interface SMIMEConstants {
   String CONTENTTYPE_MULTIPART_SIGNED = "multipart/signed";
   String CONTENTTYPE_APPLICATION_XPKCS7MIME = "application/x-pkcs7-mime";
   String CONTENTTYPE_APPLICATION_PKCS7MIME = "application/pkcs7-mime";
   String SECURITY_ENCODING_SMIME = "smime";
   byte[] SECURITY_ENCODING_SMIME_BYTES;
   String ENHANCED_CONTENT_TYPE_SMIME = "text/plain/smime";
   String SECURITY_ENCODING_SMIME_NOVERIFY_TOOLONG = "smime;nv=mtl";
   byte[] SECURITY_ENCODING_SMIME_NOVERIFY_TOOLONG_BYTES;
   String ENHANCED_CONTENT_TYPE_SMIME_NOVERIFY_TOOLONG = "text/plain/smime;nv=mtl";
   String SECURITY_ENCODING_SMIME_NOVERIFY_NOATTACH = "smime;nv=na";
   byte[] SECURITY_ENCODING_SMIME_NOVERIFY_NOATTACH_BYTES;
   String ENHANCED_CONTENT_TYPE_SMIME_NOVERIFY_NOATTACH = "text/plain/smime;nv=na";
   long PER_MESSAGE_OPTIONS = 7230255881560133169L;
   long EVENT_LOGGER_GUID = -2021078804619282789L;
   boolean INCLUDE_CERTS_PIN_DEFAULT = false;
   boolean INCLUDE_CERTS_EMAIL_DEFAULT = true;
   int MAX_NUM_SIGNED_RECEIPTS_TO_CACHE = 50;
   int DEFAULT_RECIPIENT_CONTENT_CIPHERS = 240;
   int SUPPORTED_RECIPIENT_CONTENT_CIPHERS = 255;
}
