package net.rim.device.apps.internal.sms;

public interface SMSEventViewerEvents {
   long SMS_EVENT_LOGGER_GUID;
   String SMS_EVENT_LOGGER_TITLE;
   int UPDATE_TRANSMISSION_STATUS_CALLED;
   int UPDATE_TRANSMISSION_STATUS_ITEM_NOT_FOUND;
   int UPDATE_TRANSMISSION_STATUS_UNKNOWN_STATUS;
   int CONNECTOR_OPEN_FAILED;
   int RECEIVE_IO_EXCEPTION;
   int TRANSMIT_IO_EXCEPTION;
   int FOLDERS_NOT_FOUND;
   int DELETED_MESSAGE_IN_SAME_SLOT;
   int DELETED_MESSAGE_MATCHING_REPLACE_TYPE;
   int MESSAGE_NOT_STORED;
   int MESSAGE_RECEIVED;
   int SEGMENT_RECEIVED;
   int IGNORING_DUPLICATE_MESSAGE;
   int CPHS_VMI_ON;
   int CPHS_VMI_OFF;
   int MESSAGE_WAITING_GROUP_VMI_ON;
   int MESSAGE_WAITING_GROUP_VMI_OFF;
   int SIM_DELETE_FAILED;
   int SIM_DELETE_QUEUED;
   int SIM_QUEUED_DELETE_SUCCEEDED;
   int SIM_QUEUED_DELETE_FAILED;
   int SIM_MARK_AS_READ_FAILED;
   int SIM_MARK_AS_READ_QUEUED;
   int SIM_QUEUED_MARK_AS_READ_SUCCEEDED;
   int SIM_QUEUED_MARK_AS_READ_FAILED;
   int UDH_MESSAGE_WAITING;
   int MOBILE_ORIGINATED_MESSAGE_IGNORED;
}
