package net.rim.device.cldc.io.waphttp;

import net.rim.device.api.io.http.HttpProtocolConstants;

public final class HeaderDecoder implements HttpProtocolConstants {
   public static final String getContentTypeAssignedName(int assignedValue) {
      switch (assignedValue) {
         case -1:
            return "?";
         case 0:
         default:
            return "*/*";
         case 1:
            return "text/*";
         case 2:
            return "text/html";
         case 3:
            return "text/plain";
         case 4:
            return "text/x-hdml";
         case 5:
            return "text/x-ttml";
         case 6:
            return "text/x-vcalendar";
         case 7:
            return "text/x-vcard";
         case 8:
            return "text/vnd.wap.wml";
         case 9:
            return "text/vnd.wap.wmlscript";
         case 10:
            return "text/vnd.wap.wta-event";
         case 11:
            return "multipart/*";
         case 12:
            return "multipart/mixed";
         case 13:
            return "multipart/form-data";
         case 14:
            return "multipart/byterantes";
         case 15:
            return "multipart/alternative";
         case 16:
            return "application/*";
         case 17:
            return "application/java-vm";
         case 18:
            return "application/x-www-form-urlencoded";
         case 19:
            return "application/x-hdmlc";
         case 20:
            return "application/vnd.wap.wmlc";
         case 21:
            return "application/vnd.wap.wmlscriptc";
         case 22:
            return "application/vnd.wap.wta-eventc";
         case 23:
            return "application/vnd.wap.uaprof";
         case 24:
            return "application/vnd.wap.wtls-ca-certificate";
         case 25:
            return "application/vnd.wap.wtls-user-certificate";
         case 26:
            return "application/x-x509-ca-cert";
         case 27:
            return "application/x-x509-user-cert";
         case 28:
            return "image/*";
         case 29:
            return "image/gif";
         case 30:
            return "image/jpeg";
         case 31:
            return "image/tiff";
         case 32:
            return "image/png";
         case 33:
            return "image/vnd.wap.wbmp";
         case 34:
            return "application/vnd.wap.multipart.*";
         case 35:
            return "application/vnd.wap.multipart.mixed";
         case 36:
            return "application/vnd.wap.multipart.form-data";
         case 37:
            return "application/vnd.wap.multipart.byteranges";
         case 38:
            return "application/vnd.wap.multipart.alternative";
         case 39:
            return "application/xml";
         case 40:
            return "text/xml";
         case 41:
            return "application/vnd.wap.wbxml";
         case 42:
            return "application/x-x968-cross-cert";
         case 43:
            return "application/x-x968-ca-cert";
         case 44:
            return "application/x-x968-user-cert";
         case 45:
            return "text/vnd.wap.si";
         case 46:
            return "application/vnd.wap.sic";
         case 47:
            return "text/vnd.wap.sl";
         case 48:
            return "application/vnd.wap.slc";
         case 49:
            return "text/vnd.wap.co";
         case 50:
            return "application/vnd.wap.coc";
         case 51:
            return "application/vnd.wap.multipart.related";
         case 52:
            return "application/vnd.wap.sia";
         case 53:
            return "text/vnd.wap.connectivity-xml";
         case 54:
            return "application/vnd.wap.connectivity-wbxml";
         case 55:
            return "application/pkcs7-mime";
         case 56:
            return "application/vnd.wap.hashed-certificate";
         case 57:
            return "application/vnd.wap.signed-certificate";
         case 58:
            return "application/vnd.wap.cert-response";
         case 59:
            return "application/xhtml+xml";
         case 60:
            return "application/wml+xml";
         case 61:
            return "text/css";
         case 62:
            return "application/vnd.wap.mms-message";
         case 63:
            return "application/vnd.wap.rollover-certificate";
         case 64:
            return "application/vnd.wap.locc+wbxml";
         case 65:
            return "application/vnd.wap.loc+xml";
         case 66:
            return "application/vnd.syncml.dm+wbxml";
         case 67:
            return "application/vnd.syncml.dm+xml";
         case 68:
            return "application/vnd.syncml.notification";
         case 69:
            return "application/vnd.wap.xhtml+xml";
         case 70:
            return "application/vnd.wv.csp.cir";
         case 71:
            return "application/vnd.oma.dd+xml";
         case 72:
            return "application/vnd.oma.drm.message";
         case 73:
            return "application/vnd.oma.drm.content";
         case 74:
            return "application/vnd.oma.drm.rights+xml";
         case 75:
            return "application/vnd.oma.drm.rights+wbxml";
      }
   }

   public static final String getPushAppAssignedName(int assignedValue) {
      switch (assignedValue) {
         case 0:
            return "x-wap-application:*";
         case 1:
            return "x-wap-application:push.sia";
         case 2:
            return "x-wap-application:wml.ua";
         case 3:
            return "x-wap-application:wta.ua";
         case 4:
            return "x-wap-application:mms.ua";
         case 5:
            return "x-wap-application:push.syncml";
         case 6:
            return "x-wap-application:loc.ua";
         case 7:
            return "x-wap-application:syncml.dm";
         case 8:
            return "x-wap-application:drm.ua";
         case 9:
            return "x-wap-application:emn.ua";
         case 10:
            return "x-wap-application:wv.ua";
         case 32768:
            return "x-wap-microsoft:localcontent.ua";
         case 32769:
            return "x-wap-microsoft:IMclient.ua";
         case 32770:
            return "x-wap-docomo:imode.mail.ua";
         case 32771:
            return "x-wap-docomo:imode.mr.ua";
         case 32772:
            return "x-wap-docomo:imode.mf.ua";
         case 32773:
            return "x-motorola:location.ua";
         case 32774:
            return "x-motorola:now.ua";
         case 32775:
            return "x-motorola:otaprov.ua";
         case 32776:
            return "x-motorola:browser.ua";
         case 32777:
            return "x-motorola:splash.ua";
         case 32779:
            return "x-wap-nai:mvsw.command";
         case 32784:
            return "x-wap-openwave:iota.ua";
         default:
            return Integer.toString(assignedValue);
      }
   }
}
