package net.rim.device.theme.bbdimension_zen_320x240_b;

import net.rim.device.apps.api.ribbon.ApplicationFolder;
import net.rim.device.apps.api.ribbon.ApplicationHierarchy;
import net.rim.device.apps.api.ribbon.ApplicationProperties;

final class ApplicationHierarchyInstance extends ApplicationHierarchy {
   ApplicationHierarchyInstance() {
      super("BlackBerry");
      this.setAllowMoveIcons(true);
      this.setAllowHideIcons(true);
      this.setDefaultFolderName("");
      ApplicationFolder folder = this.getRootFolder();
      folder.setAllowMoveIcons(true);
      folder.setAllowHideIcons(true);
      ApplicationProperties properties = this.createApplicationProperties("net_rim_bb_otaupgrade.available");
      properties.setPosition(1);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_otaupgrade.download");
      properties.setPosition(1);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_otaupgrade.stopped");
      properties.setPosition(1);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_otaupgrade.ready");
      properties.setPosition(1);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_activation.Activation");
      properties.setPosition(4);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_setupwizard_app.SetupWizard");
      properties.setPosition(5);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_messaging_app.Messages");
      properties.setPosition(8);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_messaging_app.Messages.service");
      properties.setPosition(9);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_phone_ptt_app.PushtoTalk");
      properties.setPosition(11);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_addressbook_app.Compose");
      properties.setPosition(18);
      properties.setVisible(false);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_messaging_app.SavedMessages");
      properties.setPosition(19);
      properties.setVisible(false);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_phone_app.Phone");
      properties.setPosition(20);
      properties.setVisible(true);
      properties.setFolderName("");
      properties.setDescriptionResource("net.rim.device.theme.bbdimension_zen_320x240_b.resource.Theme", 1);
      properties = this.createApplicationProperties("net_rim_bb_qm_peer");
      properties.setPosition(25);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_calendar_app.Calendar");
      properties.setPosition(30);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_addressbook_app.AddressBook");
      properties.setPosition(40);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_browser_daemon.single");
      properties.setPosition(50);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_browser_daemon.mds.private");
      properties.setPosition(55);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_browser_daemon.mds.public");
      properties.setPosition(60);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_browser_daemon.wap");
      properties.setPosition(65);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_lbs.LBS");
      properties.setPosition(80);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_file_explorer.Media");
      properties.setPosition(85);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_voicenotesrecorder.VoiceNotesRecorder");
      properties.setPosition(86);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_videorecorder.VideoRecorder");
      properties.setPosition(87);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_file_explorer.Music");
      properties.setPosition(89);
      properties.setVisible(false);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_file_explorer.Pictures");
      properties.setPosition(90);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_camera.Camera");
      properties.setPosition(95);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_browser_daemon.mds.public.rim");
      properties.setPosition(100);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("bbstore");
      properties.setPosition(105);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_profiles_app");
      properties.setPosition(110);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_task_app.Tasks");
      properties.setPosition(115);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_memo_app.MemoPad");
      properties.setPosition(120);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_alarm_app.Alarm");
      properties.setPosition(125);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_voicenotes.sendVoiceNote");
      properties.setPosition(130);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_vad.VoiceDialing");
      properties.setPosition(145);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_device_apps_games_brickbreaker.BrickBreaker");
      properties.setPosition(155);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_standardcalculator_app.Calculator");
      properties.setPosition(160);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_passwordkeeper");
      properties.setPosition(165);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_help.Help");
      properties.setPosition(170);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_globalsearch_app.GlobalSearch");
      properties.setPosition(175);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_browser_daemon.prov.bwc");
      properties.setPosition(248);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_options_app.Options");
      properties.setPosition(249);
      properties.setVisible(true);
      properties.setFolderName("");
      properties.setCanHide(false);
      properties = this.createApplicationProperties("net_rim_wlan_wizard");
      properties.setPosition(250);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_Bluetooth.setup");
      properties.setPosition(251);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_manage_connections.ManageConnections");
      properties.setPosition(252);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_Radio");
      properties.setPosition(253);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_Radio.on");
      properties.setPosition(253);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_Radio.off");
      properties.setPosition(253);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_LockSystem");
      properties.setPosition(254);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_PowerOff");
      properties.setPosition(255);
      properties.setVisible(true);
      properties.setFolderName("");
      properties = this.createApplicationProperties("net_rim_bb_options_app.DateTime");
      properties.setDisabled(true);
      properties = this.createApplicationProperties("net_rim_bb_options_app.Status");
      properties.setDisabled(true);
      properties = this.createApplicationProperties("net_rim_orange_homescreen.CallPlan");
      properties.setDisabled(true);
      properties = this.createApplicationProperties("net_rim_orange_homescreen.Wallpaper");
      properties.setDisabled(true);
      properties = this.createApplicationProperties("net_rim_bb_file_explorer.Music");
      properties.setDisabled(true);
      properties = this.createApplicationProperties("net_rim_bb_options_app.ScreenKeyboard");
      properties.setDisabled(true);
      properties = this.createApplicationProperties("net_rim_bb_options_app.Network");
      properties.setDisabled(true);
      properties = this.createApplicationProperties("net_rim_bb_options_app.CustomWordlist");
      properties.setDisabled(true);
      properties = this.createApplicationProperties("net_rim_bb_phone_call_log_entry.CallLog");
      properties.setDisabled(true);
      properties = this.createApplicationProperties("net_rim_bb_browser_daemon.default");
      properties.setDisabled(true);
      properties = this.createApplicationProperties("net_rim_bb_options_app.BluetoothConfig");
      properties.setDisabled(true);
   }
}
