package net.rim.device.theme.bbdimension_zen_320x240_b;

import net.rim.device.api.i18n.Locale;
import net.rim.device.api.i18n.ResourceBundle;
import net.rim.device.api.ui.theme.Theme$Factory;
import net.rim.device.api.ui.theme.Theme$Writer;
import net.rim.device.api.ui.theme.ThemeAttributeSet$Writer;
import net.rim.device.api.ui.theme.ThemeManager;
import net.rim.device.apps.api.ribbon.ApplicationHierarchy;
import net.rim.device.apps.api.ribbon.ApplicationHierarchyProvider;

public final class ThemeFactory extends Theme$Factory implements ApplicationHierarchyProvider {
   public ThemeFactory() {
      super("Bbdimension_zen_320x240_b", "");
      this.setTargetDisplay(320, 240, 16);
      this.setRemovable(false);
   }

   public static final void main(String[] args) {
      boolean addTheme = true;
      if (addTheme) {
         ThemeManager.add(new ThemeFactory());
      }
   }

   @Override
   public final String getName(Locale locale) {
      return ResourceBundle.getBundle(7546287757783908886L, "net.rim.device.theme.bbdimension_zen_320x240_b.resource.Theme").getString(0);
   }

   @Override
   public final int getPriority() {
      return 50;
   }

   @Override
   public final ApplicationHierarchy getApplicationHierarchyInfo() {
      return new ApplicationHierarchyInstance();
   }

   @Override
   public final void populate(Theme$Writer theme) {
      theme.setResourceBundle(ResourceBundle.getBundle(7546287757783908886L, "net.rim.device.theme.bbdimension_zen_320x240_b.resource.Theme"));
      theme.addResources();
      theme.setOption("FrontConvenienceKey", "net_rim_bb_camera.Camera");
      theme.setOption("SideConvenienceKey", "net_rim_vad.VoiceDialing");
      theme.setApplicationIconSize(48, 36);
      theme.addAlias("net_rim_bb_file_explorer.Pictures", "net_rim_bb_explorer_picture.Pictures");
      theme.addAlias("net_rim_bb_file_explorer.Pictures~focus", "net_rim_bb_explorer_picture.Pictures~focus");
      theme.setThumbnailName("MyThumbnail");
      theme.createBorderBitmap("popup", 14, 14, 14, 14);
      theme.createBorderBitmap("menu", 14, 14, 14, 14);
      theme.createBorderBitmap("title", 0, 0, 4, 0);
      theme.createBorderBitmap("button", 4, 9, 4, 9);
      theme.createBorderBitmap("button~focus", 4, 9, 4, 9);
      theme.createBorderSimple("global-border", 1, 1, 1, 1);
      theme.createBorderSimple("inplace", 1, 1, 1, 1);
      theme.createBorderBitmap("calendar_week-busy", 2, 2, 2, 2);
      theme.createBorderBitmap("calendar_week-busy~focus", 2, 2, 2, 2);
      theme.createBorderBitmap("calendar_week-free", 2, 2, 2, 2);
      theme.createBorderBitmap("calendar_week-free~focus", 2, 2, 2, 2);
      theme.createBorderBitmap("calendar_week-outofoffice", 2, 2, 2, 2);
      theme.createBorderBitmap("calendar_week-outofoffice~focus", 2, 2, 2, 2);
      theme.createBorderBitmap("calendar_week-tentative", 2, 2, 2, 2);
      theme.createBorderBitmap("calendar_week-tentative~focus", 2, 2, 2, 2);
      theme.createBorderBitmap("addressbooktitle_view", 6, 9, 6, 9);
      theme.createBorderBitmap("addressbooktitle_edit", 6, 9, 6, 9);
      theme.createBorderBitmap("email_compose_header_area", 7, 9, 5, 9);
      theme.createBorderBitmap("email_compose_header_subject_area", 7, 9, 9, 9);
      theme.createBorderBitmap("email_attachment_area", 6, 9, 6, 9);
      theme.createBorderBitmap("email_header_area", 7, 9, 5, 9);
      theme.createBorderBitmap("email_header_subject_area", 7, 9, 9, 9);
      theme.createBorderBitmap("email_original_message_header", 6, 6, 6, 6);
      theme.createBorderSimple("email_address_tooltip", 1, 1, 1, 1);
      theme.createBorderBitmap("calendar_appointment_warning_area", 6, 9, 6, 9);
      theme.loadScrollbar(
         "media-scrollbar",
         "scrubber_v_active",
         "scrubber_h_active",
         "vertical_scroll_bar_bk",
         "horizontal_scroll_bar_bk",
         "up_active",
         "down_active",
         "left_active",
         "right_active",
         "",
         "scrubber_v_inactive",
         "scrubber_h_inactive",
         "vertical_scroll_bar_bk",
         "horizontal_scroll_bar_bk",
         "up_inactive",
         "down_inactive",
         "left_inactive",
         "right_inactive",
         ""
      );
      ThemeAttributeSet$Writer attr = theme.createThemeAttributeSetWriter("");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      attr.setColor(5, 16777215);
      attr.setColor(4, 8882055);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-block-name");
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_view");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-block-name-edit");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_edit");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-communication");
      attr.setColor(0, 16777215);
      attr.setEdges(0, 0, 0, 0, 3);
      attr.setBorder("addressbooktitle_view");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-communication-edit");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_edit");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-company");
      attr.setFontSize(-1, 2, true);
      attr.setEdges(0, 0, 0, 0, 3);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-list-line1");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-list-line2");
      attr.setFontSize(-1, 2, true);
      attr.setColor(1, 8355711);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-mailingaddress");
      attr.setEdges(0, 0, 0, 0, 3);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_view");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-mailingaddress-edit");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_edit");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-mailingaddress-title");
      attr.setEdges(0, 0, 0, 0, 3);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-name");
      attr.setFontStyle(1);
      attr.setEdges(0, 0, 0, 0, 3);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-other");
      attr.setEdges(0, 0, 0, 0, 3);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_view");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-other-edit");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_edit");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-picture");
      attr.setEdges(0, 3, 3, 3, 3);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-row-even");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setColor(5, 16777215);
      attr.setColor(4, 7895175);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-row-odd");
      attr.setColor(1, 0);
      attr.setColor(0, 16250871);
      attr.setColor(3, 0);
      attr.setColor(2, 13421772);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("addressbook-title");
      attr.setFontSize(-1, 2, true);
      attr.setEdges(0, 0, 0, 0, 3);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("agenda-header");
      attr.setFontStyle(1);
      attr.setColor(1, 16777215);
      attr.setColor(0, 13421772);
      attr.setBackgroundImage("agenda_background_header.png");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("application-menu");
      attr.setFontStyle(1);
      attr.setColor(1, 4473924);
      attr.setColor(0, 16777215);
      attr.setBackgroundImage("background_popup.png");
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      attr.setEdges(2, 0, 0, 0, 0);
      attr.setEdges(0, 0, 0, 0, 0);
      attr.setBorder("popup");
      attr.setPosition(0, 0, 212, 216);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("application-menu-icon");
      attr.setEdges(2, 0, 0, 0, 0);
      attr.setEdges(0, 0, 0, 0, 0);
      attr.setPosition(0, 50, 320, 190);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("appointments");
      attr.setColor(1, 0);
      attr.setColor(0, 16120575);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("banner");
      attr.setLayout("banner.pme");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("banner#activecall");
      attr.setLayout("activecallbanner.pme");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("bbmessenger-branch");
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("bbmessenger-branchtitle");
      attr.setColor(0, 16777215);
      attr.setColor(1, 23776);
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("bbmessenger-contactleaf");
      attr.setColor(1, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("bbmessenger-contacttree");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("bbmessenger-conversationleaf");
      attr.setColor(1, 0);
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("bbmessenger-conversationscreen");
      attr.setColor(1, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("bbmessenger-emptyleaf");
      attr.setColor(1, 8421504);
      attr.setFontStyle(2);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("bbmessenger-messagelist");
      attr.setColor(0, 16777215);
      attr.setColor(1, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("bbmessenger-newmessage");
      attr.setColor(0, 12572407);
      attr.setColor(1, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("bbmessenger-newrequestleaf");
      attr.setColor(1, 16711680);
      attr.setFontStyle(2);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-button");
      attr.setBorder("browser-button");
      attr.setColor(3, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-button:active");
      attr.setBorder("browser-button~active");
      attr.setColor(1, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-button:disabled");
      attr.setBorder("browser-button");
      attr.setColor(1, 10657952);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-button:disabled-focus");
      attr.setBorder("browser-button~focus");
      attr.setColor(1, 10657952);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-button:focus");
      attr.setBorder("browser-button~focus");
      attr.setColor(1, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-edit");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setFocusStyle(0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-footer");
      attr.setColor(1, 16777215);
      attr.setColor(0, 8882055);
      attr.setColor(3, 16777215);
      attr.setColor(2, 16777215);
      attr.setColor(5, 16777215);
      attr.setColor(4, 1082623);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-scrollbar");
      attr.setColor(1, 8882055);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-startup-background");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-startup-entry");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-startup-header");
      attr.setFontStyle(1);
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBackgroundImage("background_browser_bookmarks.png");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-startup-urlbg");
      attr.setColor(1, 0);
      attr.setColor(0, 15923199);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("browser-startup-urlentry");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setEdges(0, 0, 0, 0, 0);
      attr.setEdges(2, 3, 0, 3, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("button");
      attr.setBorder("button");
      attr.setColor(1, 13092807);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("button:focus");
      attr.setBorder("button~focus");
      attr.setColor(1, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("calendar-appointment-section-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_edit");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("calendar-appointment-subject-text");
      attr.setFontStyle(1);
      attr.setEdges(2, 0, 0, 4, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("calendar-appointment-warning-area");
      attr.setFontStyle(1);
      attr.setColor(0, 16777177);
      attr.setColor(1, 0);
      attr.setBorder("calendar_appointment_warning_area");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("camera-banner");
      attr.setLayout("media-banner.pme");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("camera-capture");
      attr.setLayout("capture_bar.pme");
      attr.setColor(0, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("camera-hint");
      attr.setFontFamily("MediaMedium");
      attr.setAltFontFamily("BBClarity");
      attr.setColor(0, 8421504);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("camera-preview");
      attr.setLayout("processbar.pme");
      attr.setColor(0, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("client");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("client#activecall");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("client#activecallnotes");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("client#calculator");
      attr.setColor(1, 0);
      attr.setBackgroundImage("background_calculator.png");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("conflicting-appointments");
      attr.setColor(1, 0);
      attr.setColor(0, 16120575);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("day");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("day-allday");
      attr.setColor(1, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("day-appointment-bar");
      attr.setColor(1, 3451392);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("day-current-time");
      attr.setColor(1, 16711680);
      attr.setColor(0, 1082623);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("day-focus-hilight");
      attr.setColor(1, 16777215);
      attr.setColor(0, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("day-indicator-selected");
      attr.setColor(1, 16777215);
      attr.setColor(0, 6579300);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("day-line");
      attr.setColor(1, 13421772);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("default-font");
      attr.setFontFamily("BBAlpha Sans");
      attr.setFontSize(9, 2, false);
      attr.setFontStyle(0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-address-tooltip");
      attr.setColor(1, 0);
      attr.setColor(0, 15461355);
      attr.setEdges(2, 2, 2, 2, 2);
      attr.setEdges(0, 1, 1, 1, 1);
      attr.setBorder("email_address_tooltip");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-address-tooltip-address-text");
      attr.setFontSize(-1, 2, true);
      attr.setFontStyle(0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-address-tooltip-name-text");
      attr.setFontSize(-1, 2, true);
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-address-tooltip-photo");
      attr.setEdges(0, 0, 4, 0, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-attachment-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("email_attachment_area");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-attachment-status-text");
      attr.setColor(1, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-attachment-text");
      attr.setColor(1, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-body-area");
      attr.setColor(1, 0);
      attr.setEdges(0, 0, 4, 0, 4);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-compose-attachment-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("email_attachment_area");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-compose-body-area");
      attr.setColor(1, 0);
      attr.setEdges(0, 0, 4, 0, 4);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-compose-header-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("email_compose_header_area");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-compose-header-mailbox-text");
      attr.setEdges(0, 0, 0, 7, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-compose-subject-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("email_compose_header_subject_area");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-compose-subject-text");
      attr.setColor(1, 0);
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-editor-screen");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-header-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("email_header_area");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-header-first-recipient-text");
      attr.setColor(1, 4144959);
      attr.setEdges(0, 7, 0, 0, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-header-text");
      attr.setColor(1, 4144959);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-message-body");
      attr.setEdges(0, 4, 1, 4, 1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-more-status-text");
      attr.setColor(1, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-original-message");
      attr.setColor(1, 4144959);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-original-message-header-area");
      attr.setColor(1, 4144959);
      attr.setColor(0, 16777215);
      attr.setBorder("email_original_message_header");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-original-message-separator");
      attr.setColor(1, 23776);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-subject-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("email_header_subject_area");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-subject-text");
      attr.setColor(1, 0);
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-timestamp-text");
      attr.setFontSize(-2, 2, true);
      attr.setColor(1, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("email-viewer-screen");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("event-viewer-screen");
      attr.setColor(1, 0);
      attr.setColor(0, 15197159);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("explorer-banner");
      attr.setLayout("media-banner.pme");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("fileviewtooltip");
      attr.setColor(1, 0);
      attr.setColor(0, 15461355);
      attr.setEdges(0, 1, 1, 0, 1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("folderview");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBackgroundImage("background_folderview.png");
      attr.setPosition(0, 65, 320, 26);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("free-time-seperators");
      attr.setColor(1, 9079434);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("gauge-bar");
      attr.setColor(0, 16777215);
      attr.setColor(1, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("gauge-fill");
      attr.setColor(5, 16777215);
      attr.setColor(4, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("header");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBackgroundImage("background_header.png");
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("homescreen");
      attr.setLayout("homescreen.pme");
      attr.setColor(0, 16777215);
      attr.setBackgroundImage("background_homescreen.png");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("idle");
      attr.setLayout("lockedscreen.pme");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("idle");
      attr.setLayout("lockedscreen.pme");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("indicator");
      attr.setColor(1, 16777215);
      attr.setColor(0, 8882055);
      attr.setFontFamily("BannerUnread");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("inplace");
      attr.setColor(1, 4473924);
      attr.setBackgroundImage("background_popup.png");
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      attr.setEdges(0, 1, 1, 1, 1);
      attr.setBorder("inplace");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("input-method-popup");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setEdges(0, 1, 1, 1, 1);
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 0);
      attr.setBorder("popup");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("list#phonestatusfield");
      attr.setColor(1, 23776);
      attr.setColor(0, 16777215);
      attr.setFontFamily("BBMillbank");
      attr.setFontSize(16, 0, false);
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("list-move");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setColor(3, 0);
      attr.setColor(2, 13421772);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-find");
      attr.setFontAntialiasMode(3);
      attr.setFontSize(7, 2, false);
      attr.setFontStyle(1);
      attr.setColor(1, 16777215);
      attr.setBackgroundImage("find_banner_background.png");
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 1669552);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-hub");
      attr.setLayout("mediahub.pme");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-library-album-title");
      attr.setBackgroundImage("list_background.png");
      attr.setFocusStyle(3);
      attr.setColor(2, 1669552);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-library-banner");
      attr.setLayout("media-library-banner.pme");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-library-screen");
      attr.setBackgroundImage("list_background.png");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-library-scrollbar");
      attr.setColor(1, 8882055);
      attr.setScrollbar("media-scrollbar");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-list");
      attr.setFontAntialiasMode(3);
      attr.setFontStyle(1);
      attr.setColor(1, 16777215);
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 1669552);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-options-heading-text");
      attr.setFontAntialiasMode(3);
      attr.setFontSize(9, 2, false);
      attr.setFontStyle(1);
      attr.setColor(1, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-options-text");
      attr.setFontAntialiasMode(3);
      attr.setFontSize(8, 2, false);
      attr.setColor(1, 16777215);
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 1669552);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-player-audio-embedded");
      attr.setLayout("media_player_embed.pme");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-player-bar");
      attr.setLayout("media_player_bar.pme");
      attr.setColor(0, 8421504);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-playlist");
      attr.setFontFamily("MediaLarge");
      attr.setColor(1, 15132393);
      attr.setFocusStyle(3);
      attr.setColor(3, 15132393);
      attr.setColor(2, 1669552);
      attr.setColor(5, 13027021);
      attr.setColor(4, 13882323);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-property");
      attr.setFontSize(6, 2, false);
      attr.setColor(1, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-screen");
      attr.setColor(0, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("media-track-title");
      attr.setFontSize(8, 2, false);
      attr.setColor(1, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("mediaplayer-banner");
      attr.setLayout("mediaplayer-banner.pme");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("memo-data-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_edit");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("memo-screen");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("memo-title-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_edit");
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("menu");
      attr.setColor(1, 4473924);
      attr.setColor(0, 16777215);
      attr.setBackgroundImage("background_menu.png");
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      attr.setEdges(0, 0, 0, 5, 5);
      attr.setBorder("menu");
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("menuitem:focus");
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("messagelist-line1");
      attr.setColor(1, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("messagelist-line1-level1");
      attr.setColor(1, 16711680);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("messagelist-line2");
      attr.setColor(1, 8355711);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("messagelist-line2-level1");
      attr.setColor(1, 16728128);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("messagelist-row-even");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setColor(5, 16777215);
      attr.setColor(4, 7895175);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("messagelist-row-odd");
      attr.setColor(1, 0);
      attr.setColor(0, 16250871);
      attr.setColor(3, 0);
      attr.setColor(2, 13421772);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("month");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("month-date");
      attr.setColor(1, 0);
      attr.setColor(0, 14540253);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("month-daysofweek");
      attr.setColor(1, 16777215);
      attr.setColor(0, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("month-next-day");
      attr.setColor(1, 12566463);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("month-previous-day");
      attr.setColor(1, 12566463);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("month-title");
      attr.setColor(1, 0);
      attr.setColor(0, 12049663);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("month-today");
      attr.setColor(1, 16777215);
      attr.setColor(0, 8882055);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("month-weekday");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("month-weekend");
      attr.setColor(1, 0);
      attr.setColor(0, 14540253);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("options-section-area");
      attr.setEdges(0, 2, 2, 5, 2);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("options-section-header");
      attr.setFontSize(1, 2, true);
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("past-agenda-header");
      attr.setFontStyle(0);
      attr.setColor(1, 9079434);
      attr.setColor(0, 13421772);
      attr.setBackgroundImage("background_header.png");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("past-appointments");
      attr.setFontStyle(0);
      attr.setColor(1, 9079434);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("past-free-time-seperators");
      attr.setColor(1, 0);
      attr.setColor(0, 15658496);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("phone-dial");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("phone-hotlist-hotkey");
      attr.setColor(1, 0);
      attr.setFontFamily("BBMillbank");
      attr.setColor(3, 0);
      attr.setColor(5, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("picture-window");
      attr.setColor(0, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("popup");
      attr.setColor(1, 4473924);
      attr.setColor(0, 16777215);
      attr.setBackgroundImage("background_popup.png");
      attr.setEdges(0, 2, 2, 2, 2);
      attr.setBorder("menu");
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("popup#calldisplay");
      attr.setColor(1, 4473924);
      attr.setColor(0, 8882055);
      attr.setBackgroundImage("background_calldisplay.png");
      attr.setBorder("popup");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("popup#phonevolume");
      attr.setColor(1, 16777215);
      attr.setColor(0, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("popup#taskswitcher");
      attr.setBorder("popup");
      attr.setColor(1, 4473924);
      attr.setFontStyle(1);
      attr.setBackgroundImage("background_popup.png");
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      attr.setEdges(0, 4, 4, 4, 4);
      attr.setScrollArrow(0, "menu_up_arrow");
      attr.setScrollArrow(1, "menu_down_arrow");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("profiles-menu");
      attr.setFontStyle(1);
      attr.setColor(1, 4473924);
      attr.setColor(0, 16777215);
      attr.setBackgroundImage("background_popup.png");
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      attr.setEdges(2, 0, 0, 0, 0);
      attr.setEdges(0, 0, 0, 0, 0);
      attr.setBorder("popup");
      attr.setPosition(46, 4, 212, 216);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("profiles-menu-selected");
      attr.setFontStyle(0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("recorder-controlbar");
      attr.setLayout("controlbar.pme");
      attr.setColor(0, 8421504);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("recorder-hint");
      attr.setFontFamily("MediaMedium");
      attr.setAltFontFamily("BBClarity");
      attr.setColor(0, 8421504);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("recorder-recordbar");
      attr.setLayout("recorderbar.pme");
      attr.setColor(0, 8421504);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("recorder-screen");
      attr.setColor(0, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("separator");
      attr.setColor(1, 8882055);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("separator#banner");
      attr.setColor(1, 8882055);
      attr.setColor(0, 8882055);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("separator#title");
      attr.setColor(1, 16777215);
      attr.setColor(0, 8882055);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("status#homescreen");
      attr.setBackgroundImage("background_status.png");
      attr.setBackgroundPosition(0, 0);
      attr.setFontFamily("Homescreen");
      attr.setAltFontFamily("BBMillbank");
      attr.setFontSize(20, 0, false);
      attr.setFontStyle(1);
      attr.setColor(6, 16250871);
      attr.setColor(7, 4473924);
      attr.setFontStrokeOpacity(153);
      attr.setPosition(0, 0, 320, 32);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("status#manage-connections");
      attr.setFontStyle(1);
      attr.setColor(1, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("symbolfield");
      attr.setColor(1, 4473924);
      attr.setBackgroundImage("background_popup.png");
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("task-data-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_edit");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("task-notes-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_edit");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("task-screen");
      attr.setColor(1, 0);
      attr.setColor(0, 15197159);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("task-title-area");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setBorder("addressbooktitle_edit");
      attr.setFontStyle(1);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("title");
      attr.setFontStyle(1);
      attr.setColor(1, 4473924);
      attr.setColor(0, 16777215);
      attr.setBackgroundImage("background_title.png");
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      attr.setBorder("title");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("title#activecallnotes");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("title#phoneentry");
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("twolinebanner");
      attr.setLayout("twolinebanner.pme");
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("view-calendars-area");
      attr.setEdges(0, 2, 2, 2, 2);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("view-calendars-folder-text");
      attr.setEdges(2, 2, 0, 0, 0);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      attr.setFocusStyle(3);
      attr.setColor(3, 16777215);
      attr.setColor(2, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-allday");
      attr.setColor(1, 1082623);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-appointment-border");
      attr.setColor(1, 4579584);
      attr.setColor(0, 4579584);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-current-day");
      attr.setColor(1, 16777215);
      attr.setColor(0, 8882055);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-current-day-focus");
      attr.setColor(1, 16777215);
      attr.setColor(0, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-date");
      attr.setColor(1, 0);
      attr.setColor(0, 14540253);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-daysofweek");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-focus-hilight");
      attr.setColor(1, 16777215);
      attr.setColor(0, 23776);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-meeting");
      attr.setColor(1, 2986752);
      attr.setColor(0, 2986752);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-more");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-simple-appointment");
      attr.setColor(1, 4579584);
      attr.setColor(0, 4579584);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-time");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-view");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-weekday");
      attr.setColor(1, 0);
      attr.setColor(0, 16777215);
      theme.put(attr);
      attr = theme.createThemeAttributeSetWriter("week-weekend");
      attr.setColor(1, 0);
      attr.setColor(0, 14540253);
      theme.put(attr);
   }
}
