package net.rim.device.api.browser.field;

public interface RenderingConstants {
   int NAVIGATION_TYPE_FORWARD;
   int NAVIGATION_TYPE_BACKWARD;
   int NAVIGATION_TYPE_REFRESH;
   int NAVIGATION_TYPE_REVALIDATE;
   int NAVIGATION_TYPE_NO_CACHE;
   int NAVIGATION_MASK;
   int EMBEDDED_CONTENT;
   int BROWSER_CONTENT;
   int SHARED_MASK;
   int CLEAR_CONTEXT;
   int POSTPONE_SECONDARY_RESOURCES;
   int DISABLE_SCROLLING;
   int DRM_FORWARD_LOCK;
   int CACHED_CONTENT;
   int UPDATE_HISTORY;
   int REPLACE_HISTORY;
   int RETURN_EXPIRED;
   int DO_NOT_CACHE_RESPONSE;
}
