package net.rim.device.api.browser.field;

public interface RenderingConstants {
   int NAVIGATION_TYPE_FORWARD = 1;
   int NAVIGATION_TYPE_BACKWARD = 2;
   int NAVIGATION_TYPE_REFRESH = 3;
   int NAVIGATION_TYPE_REVALIDATE = 4;
   int NAVIGATION_TYPE_NO_CACHE = 5;
   int NAVIGATION_MASK = 7;
   int EMBEDDED_CONTENT = 16;
   int BROWSER_CONTENT = 32;
   int SHARED_MASK = 255;
   int CLEAR_CONTEXT = 256;
   int POSTPONE_SECONDARY_RESOURCES = 512;
   int DISABLE_SCROLLING = 1024;
   int DRM_FORWARD_LOCK = 2048;
   int CACHED_CONTENT = 4096;
   int UPDATE_HISTORY = 8192;
   int REPLACE_HISTORY = 16384;
   int RETURN_EXPIRED = 32768;
   int DO_NOT_CACHE_RESPONSE = 65536;
}
