package net.rim.device.internal.resource.crypto;

public interface CertificateServersOptionsResource {
   long BUNDLE_ID;
   String BUNDLE_NAME;
   int SERVER_OPTIONS_LDAP_SERVERS;
   int SERVER_OPTIONS_DISPLAY_SERVER;
   int SERVER_OPTIONS_SERVER_TYPE;
   int SERVER_OPTIONS_CONN;
   int ENTER_FRIENDLY_NAME;
   int SERVER_OPTIONS_PORT;
   int SERVER_OPTIONS_AUTH;
   int ENTER_SERVER_URL;
   int SERVER_OPTIONS_CRL_SERVER;
   int SERVER_OPTIONS_TITLE;
   int SERVER_OPTIONS_OCSP_SERVER;
   int SERVER_OPTIONS_IMPORT_SERVER;
   int ENTER_PORT;
   int SERVER_OPTIONS_EMAIL_SERVER;
   int SERVER_OPTIONS_CONN_TYPES;
   int SERVER_OPTIONS_NO_SERVERS;
   int ENTER_BASE_QUERY;
   int ENTER_SERVER_NAME;
   int SERVER_OPTIONS_CONFIRM_DELETE;
   int SERVER_OPTIONS_NEW_SERVER;
   int SERVER_OPTIONS_CRL_SERVERS;
   int SERVER_OPTIONS_LDAP_SERVER;
   int SERVER_OPTIONS_OCSP_SERVERS;
   int SERVER_OPTIONS_BASE_QUERY;
   int SERVER_OPTIONS_FRIENDLY_NAME;
   int SERVER_OPTIONS_PIN_SERVER;
   int SERVER_OPTIONS_SERVER_NAME;
   int SERVER_OPTIONS_NONE;
   int SERVER_OPTIONS_AUTH_TYPES;
   int SERVER_OPTIONS_SERVER_URL;
}
