package net.rim.device.internal.resource.crypto;

public interface CertificateServersOptionsResource {
   long BUNDLE_ID = -3843310740975580338L;
   String BUNDLE_NAME = "net.rim.device.internal.resource.crypto.CertificateServersOptions";
   int SERVER_OPTIONS_LDAP_SERVERS = 102;
   int SERVER_OPTIONS_DISPLAY_SERVER = 107;
   int SERVER_OPTIONS_SERVER_TYPE = 1;
   int SERVER_OPTIONS_CONN = 120;
   int ENTER_FRIENDLY_NAME = 115;
   int SERVER_OPTIONS_PORT = 6;
   int SERVER_OPTIONS_AUTH = 118;
   int ENTER_SERVER_URL = 117;
   int SERVER_OPTIONS_CRL_SERVER = 109;
   int SERVER_OPTIONS_TITLE = 401;
   int SERVER_OPTIONS_OCSP_SERVER = 110;
   int SERVER_OPTIONS_IMPORT_SERVER = 108;
   int ENTER_PORT = 116;
   int SERVER_OPTIONS_EMAIL_SERVER = 113;
   int SERVER_OPTIONS_CONN_TYPES = 121;
   int SERVER_OPTIONS_NO_SERVERS = 112;
   int ENTER_BASE_QUERY = 114;
   int ENTER_SERVER_NAME = 10;
   int SERVER_OPTIONS_CONFIRM_DELETE = 215;
   int SERVER_OPTIONS_NEW_SERVER = 0;
   int SERVER_OPTIONS_CRL_SERVERS = 105;
   int SERVER_OPTIONS_LDAP_SERVER = 111;
   int SERVER_OPTIONS_OCSP_SERVERS = 104;
   int SERVER_OPTIONS_BASE_QUERY = 5;
   int SERVER_OPTIONS_FRIENDLY_NAME = 4;
   int SERVER_OPTIONS_PIN_SERVER = 106;
   int SERVER_OPTIONS_SERVER_NAME = 2;
   int SERVER_OPTIONS_NONE = 103;
   int SERVER_OPTIONS_AUTH_TYPES = 119;
   int SERVER_OPTIONS_SERVER_URL = 3;
}
