package net.rim.device.internal.resource.crypto;

public interface PGPResource {
   long BUNDLE_ID;
   String BUNDLE_NAME;
   int PGP_ENTER_PASSWORD_DECRYPT_KEY;
   int SUBKEYID_LABEL_FIELD;
   int PGP_ENTER_PASSWORD_DECRYPT_KEY_WITH_NAME;
   int CERTINFO_WARNING_UNVERIFIED;
   int CERTINFO_WARNING_WEAK;
   int REPLACE_KEY;
   int PGP_KEY_STORE;
   int PGP_ENTER_PASSWORD_DECRYPT_MESSAGE;
   int PGP_PASSPHRASE_INCORRECT_PREFIX;
   int CERTINFO_FINGERPRINT;
   int CERTINFO_WARNING_REVOKED;
   int CERTINFO_WARNING_EXPIRED;
   int CERTINFO_WARNING_UNKNOWN;
   int CERTINFO_VIEW_SUBKEY;
   int PGPINFO_PARENT_KEY;
   int CREATION_FIELD_LABEL;
   int USER_ID;
   int CERTINFO_PHOTOGRAPH;
   int PGP_ENTER_PASSWORD_DECRYPT_MESSAGE_WITH_SUBJECT;
   int CERTINFO_WARNING_NOT_TRUSTED;
   int CERTINFO_WARNING_STALE;
   int CERTINFO_SIGNER;
   int CERTINFO_VIEW_SIGNER;
   int CERTINFO_USERID;
}
