package net.rim.device.internal.resource.crypto;

public interface WTLSResource {
   long BUNDLE_ID;
   String BUNDLE_NAME;
   int CERT_REVOKED;
   int OPTIONS_CLIENT_ID_TYPES;
   int PURGE_NV_STORE;
   int CHOICES;
   int OPTIONS_PROMPT_FOR_SERVER_TRUST;
   int YES_NO_NEVER;
   int OPTIONS_TRUST_CERTIFICATES;
   int OPTIONS_ENTER_PASSWORD;
   int NOT_VERIFIED;
   int EXPORT_SECURITY;
   int OPTIONS_CLIENT_VALUE;
   int OPTIONS_EXCEED_WARNING;
   int CERT_EXPIRED;
   int OPTIONS_WEAK_STRONG;
   int OPTIONS_CLIENT_ID_TYPES_GSM;
   int OPTIONS_CLIENT_ID_TYPES_CDMA;
   int NOT_TRUSTED;
   int OPTIONS_ENCRYPTION_STRENGTH;
   int OPTIONS_TITLE;
   int OPTIONS_CLIENT_ID_LABEL;
}
