package net.rim.device.apps.internal.resource.crypto;

public interface CryptoCommonResource {
   long BUNDLE_ID = 6923097978240753508L;
   String BUNDLE_NAME = "net.rim.device.apps.internal.resource.crypto.CryptoCommon";
   int TRUST_ENTIRE_CHAIN_QUESTION = 28;
   int IMPORT_CERTIFICATE = 21;
   int UNABLE_TO_FETCH_STATUS = 2;
   int EMAIL_CERTIFICATE = 26;
   int TRUST_CERTIFICATE = 30;
   int SEND_VIA_EMAIL = 31;
   int CERTIFICATE_LOWER_SINGULAR = 10;
   int PIN_CERTIFICATE = 27;
   int CERTIFICATE_LOWER_PLURAL = 9;
   int PGP_KEY_LOWER_SINGULAR = 14;
   int PGP_KEY_UPPER_SINGULAR = 16;
   int PASSWORD_WIZARD_INCORRECT_PASSWORD = 4;
   int DISPLAY_CERTIFICATE = 20;
   int RETRIEVE_PGP_ATTACHMENT = 23;
   int SELECT_CERTIFICATES_TO_ATTACH = 19;
   int PASSWORD_WIZARD_ENTER_PASSWORD = 3;
   int RETRIEVE_CERTIFICATE = 22;
   int NO_CERTIFICATES_TO_ATTACH = 18;
   int IMPORT_CERTIFICATE_X509_EMBEDDED = 33;
   int SECURITY_EXCEPTION_TRUSTED_KEYSTORE = 6;
   int ATTACH_CERTIFICATES = 17;
   int TRUST_CERTIFICATE_QUESTION = 8;
   int PGP_KEY_LOWER_PLURAL = 13;
   int IMPORT_CERTIFICATE_NOT_VERIFY = 7;
   int CERTIFICATE_UPPER_SINGULAR = 12;
   int UNSUPPORTED_PGP_ATTACHMENT = 25;
   int TRUSTED_CERTIFICATE_NOT_ADDED = 29;
   int SEND_VIA_PIN = 32;
   int UNSUPPORTED_CERTIFICATE_FORMAT = 24;
   int CERTIFICATE_UPPER_PLURAL = 11;
   int PGP_KEY_UPPER_PLURAL = 15;
   int SMART_CARD_CERT_IMPORT_PLEASE_WAIT = 0;
}
