package net.rim.device.apps.internal.resource.crypto;

public interface CryptoCommonResource {
   long BUNDLE_ID;
   String BUNDLE_NAME;
   int TRUST_ENTIRE_CHAIN_QUESTION;
   int IMPORT_CERTIFICATE;
   int UNABLE_TO_FETCH_STATUS;
   int EMAIL_CERTIFICATE;
   int TRUST_CERTIFICATE;
   int SEND_VIA_EMAIL;
   int CERTIFICATE_LOWER_SINGULAR;
   int PIN_CERTIFICATE;
   int CERTIFICATE_LOWER_PLURAL;
   int PGP_KEY_LOWER_SINGULAR;
   int PGP_KEY_UPPER_SINGULAR;
   int PASSWORD_WIZARD_INCORRECT_PASSWORD;
   int DISPLAY_CERTIFICATE;
   int RETRIEVE_PGP_ATTACHMENT;
   int SELECT_CERTIFICATES_TO_ATTACH;
   int PASSWORD_WIZARD_ENTER_PASSWORD;
   int RETRIEVE_CERTIFICATE;
   int NO_CERTIFICATES_TO_ATTACH;
   int IMPORT_CERTIFICATE_X509_EMBEDDED;
   int SECURITY_EXCEPTION_TRUSTED_KEYSTORE;
   int ATTACH_CERTIFICATES;
   int TRUST_CERTIFICATE_QUESTION;
   int PGP_KEY_LOWER_PLURAL;
   int IMPORT_CERTIFICATE_NOT_VERIFY;
   int CERTIFICATE_UPPER_SINGULAR;
   int UNSUPPORTED_PGP_ATTACHMENT;
   int TRUSTED_CERTIFICATE_NOT_ADDED;
   int SEND_VIA_PIN;
   int UNSUPPORTED_CERTIFICATE_FORMAT;
   int CERTIFICATE_UPPER_PLURAL;
   int PGP_KEY_UPPER_PLURAL;
   int SMART_CARD_CERT_IMPORT_PLEASE_WAIT;
}
