package net.rim.device.apps.internal.secureemail.encodings.pgp;

public interface PGPAppPolicy {
   int PGP_MIN_STRONG_DH_KEY_LENGTH = 1;
   int FORCE_PGP_DIGITAL_SIGNATURE = 2;
   int FORCE_PGP_ENCRYPTED_EMAIL = 3;
   int PGP_BCC_ADDRESS = 4;
   int PGP_ALLOWED_CONTENT_CIPHERS = 5;
   int PGP_MIN_STRONG_RSA_KEY_LENGTH = 6;
   int PGP_MIN_STRONG_DSA_KEY_LENGTH = 7;
   int PGP_UNIVERSAL_SERVER_ADDRESS = 8;
   int PGP_UNIVERSAL_SERVER_ENROLLMENT_TYPE = 9;
   int PGP_UNIVERSAL_POLICY_CACHE_TIMEOUT = 10;
   int PGP_UNIVERSAL_SERVER_ENROLLMENT_TYPE_USERNAMEPASSWORD = 0;
   int PGP_UNIVERSAL_SERVER_ENROLLMENT_TYPE_EMAIL = 1;
   int PGP_MIN_STRONG_DH_KEY_LENGTH_DEFAULT = 1024;
   int PGP_MIN_STRONG_ECC_KEY_LENGTH_DEFAULT = 163;
   boolean FORCE_PGP_DIGITAL_SIGNATURE_DEFAULT = false;
   boolean FORCE_PGP_ENCRYPTED_EMAIL_DEFAULT = false;
   int PGP_ALLOWED_CONTENT_CIPHERS_DEFAULT = 63;
   int PGP_MIN_STRONG_RSA_KEY_LENGTH_DEFAULT = 1024;
   int PGP_MIN_STRONG_DSA_KEY_LENGTH_DEFAULT = 1024;
   int PGP_UNIVERSAL_SERVER_ENROLLMENT_TYPE_DEFAULT = 1;
   int PGP_UNIVERSAL_POLICY_CACHE_TIMEOUT_DEFAULT = 24;
}
