package net.rim.device.apps.internal.secureemail.encodings.pgp;

public interface PGPAppPolicy {
   int PGP_MIN_STRONG_DH_KEY_LENGTH;
   int FORCE_PGP_DIGITAL_SIGNATURE;
   int FORCE_PGP_ENCRYPTED_EMAIL;
   int PGP_BCC_ADDRESS;
   int PGP_ALLOWED_CONTENT_CIPHERS;
   int PGP_MIN_STRONG_RSA_KEY_LENGTH;
   int PGP_MIN_STRONG_DSA_KEY_LENGTH;
   int PGP_UNIVERSAL_SERVER_ADDRESS;
   int PGP_UNIVERSAL_SERVER_ENROLLMENT_TYPE;
   int PGP_UNIVERSAL_POLICY_CACHE_TIMEOUT;
   int PGP_UNIVERSAL_SERVER_ENROLLMENT_TYPE_USERNAMEPASSWORD;
   int PGP_UNIVERSAL_SERVER_ENROLLMENT_TYPE_EMAIL;
   int PGP_MIN_STRONG_DH_KEY_LENGTH_DEFAULT;
   int PGP_MIN_STRONG_ECC_KEY_LENGTH_DEFAULT;
   boolean FORCE_PGP_DIGITAL_SIGNATURE_DEFAULT;
   boolean FORCE_PGP_ENCRYPTED_EMAIL_DEFAULT;
   int PGP_ALLOWED_CONTENT_CIPHERS_DEFAULT;
   int PGP_MIN_STRONG_RSA_KEY_LENGTH_DEFAULT;
   int PGP_MIN_STRONG_DSA_KEY_LENGTH_DEFAULT;
   int PGP_UNIVERSAL_SERVER_ENROLLMENT_TYPE_DEFAULT;
   int PGP_UNIVERSAL_POLICY_CACHE_TIMEOUT_DEFAULT;
}
