package com.fourthpass.wapstack;

public interface WSConstants {
   short DEFAULT_WSP_PDU_BUFFER_SIZE;
   int DEFAULT_WTP_PDU_BUFFER_SIZE;
   int DEFAULT_WTP_USERDATA_BUFFER_SIZE;
   int PORT_WAP_CONNECTIONLESS;
   int PORT_SWAP_CONNECTIONLESS;
   int PORT_WAP_SESSION;
   int PORT_SWAP_SESSION;
   int PORT_WAP_VCARD;
   int PORT_SWAP_VCARD;
   int PORT_WAP_VCAL;
   int PORT_SWAP_VCAL;
   int PORT_PUSH_NOTIFY;
   int PORT_SPUSH_NOTIFY;
   int PORT_DEFAULT_LOCAL;
   byte CAPABILITY_CLIENT_SDU_SIZE;
   byte CAPABILITY_SERVER_SDU_SIZE;
   byte CAPABILITY_PROTOCOL_OPTIONS;
   byte CAPABILITY_METHOD_MOR;
   byte CAPABILITY_PUSH_MOR;
   byte CAPABILITY_EXTENDED_METHODS;
   byte CAPABILITY_HEADER_CODE_PAGES;
   byte CAPABILITY_ALIASES;
   short PROTOCOL_OPTIONS_CONFPUSH;
   short PROTOCOL_OPTIONS_PUSH;
   short PROTOCOL_OPTIONS_SESSION_RESUME;
   short PROTOCOL_OPTIONS_ACK_HEADERS;
   byte STATE_STARTED;
   byte STATE_ABORTED;
   byte STATE_FINISHED;
   byte REDIRECT_EVENT;
}
