package com.fourthpass.wapstack;

public interface WSConstants {
   short DEFAULT_WSP_PDU_BUFFER_SIZE = 64;
   int DEFAULT_WTP_PDU_BUFFER_SIZE = 64;
   int DEFAULT_WTP_USERDATA_BUFFER_SIZE = 64;
   int PORT_WAP_CONNECTIONLESS = 9200;
   int PORT_SWAP_CONNECTIONLESS = 9202;
   int PORT_WAP_SESSION = 9201;
   int PORT_SWAP_SESSION = 9203;
   int PORT_WAP_VCARD = 9204;
   int PORT_SWAP_VCARD = 9206;
   int PORT_WAP_VCAL = 9205;
   int PORT_SWAP_VCAL = 9207;
   int PORT_PUSH_NOTIFY = 4445;
   int PORT_SPUSH_NOTIFY = 3356;
   int PORT_DEFAULT_LOCAL = 5000;
   byte CAPABILITY_CLIENT_SDU_SIZE = 0;
   byte CAPABILITY_SERVER_SDU_SIZE = 1;
   byte CAPABILITY_PROTOCOL_OPTIONS = 2;
   byte CAPABILITY_METHOD_MOR = 3;
   byte CAPABILITY_PUSH_MOR = 4;
   byte CAPABILITY_EXTENDED_METHODS = 5;
   byte CAPABILITY_HEADER_CODE_PAGES = 6;
   byte CAPABILITY_ALIASES = 7;
   short PROTOCOL_OPTIONS_CONFPUSH = 128;
   short PROTOCOL_OPTIONS_PUSH = 64;
   short PROTOCOL_OPTIONS_SESSION_RESUME = 32;
   short PROTOCOL_OPTIONS_ACK_HEADERS = 16;
   byte STATE_STARTED = 20;
   byte STATE_ABORTED = 21;
   byte STATE_FINISHED = 22;
   byte REDIRECT_EVENT = 1;
}
