package net.rim.device.apps.api.utility.columninfo;

public interface MessageColumns {
   int PRIORITY_COLUMN;
   int STATUS_COLUMN;
   int TIME_COLUMN;
   int ADDRESS_COLUMN;
   int SUBJECT_COLUMN;
   int ONE_LINE_PRIORITY_COLUMN;
   int ONE_LINE_STATUS_COLUMN;
   int ONE_LINE_TIME_COLUMN;
   int ONE_LINE_ADDRESS_COLUMN;
   int ONE_LINE_SUBJECT_COLUMN;
   int TWO_LINE_PRIORITY_COLUMN;
   int TWO_LINE_STATUS_COLUMN;
   int TWO_LINE_SUBJECT_COLUMN;
   int TWO_LINE_TIME_COLUMN;
   int TWO_LINE_ADDRESS_COLUMN;
   int TWO_LINE_TIME_COLUMN_OLDUI;
   int TWO_LINE_ADDRESS_COLUMN_OLDUI;
   int TWO_LINE_SUBJECT_COLUMN_OLDUI;
}
