package net.rim.device.apps.api.transmission;

public interface EventLoggerEvents {
   int RECEIVE_THREAD_RUNNING;
   int RECEIVE_DATAGRAM_NOT_CREATED;
   int RECEIVE_WAITING_FOR_PACKET;
   int RECEIVE_PROCESSING_PACKET;
   int RECEIVE_FORWARDING_PACKET;
   int RECEIVE_CRYPTO_FAILURE;
   int RECEIVE_ERROR_SERIALIZATION_EXCEPTION;
   int RECEIVE_MORE_SERIALIZATION_EXCEPTION;
   int RECEIVE_ATTACHMENT_SERIALIZATION_EXCEPTION;
   int RECEIVE_CONVERTER_NOT_FOUND;
   int RECEIVE_UNKNOWN_PACKET_TYPE;
   int RECEIVE_DUPLICATE_DETECTED;
   int RECEIVE_MISMATCH_SERVICE_RECORD_ID;
   int RECEIVE_MISMATCH_SERVICE_RECORD_UID;
   int SEND_THREAD_RUNNING;
   int SEND_DATAGRAM_NOT_CREATED;
   int SEND_WAITING_FOR_PACKET;
   int SEND_SENDING_PACKET;
   int SEND_IO_EXCEPTION;
   int SEND_IO_EXCEPTION_DURING_WRITING;
   int SEND_NOTHING_TO_SEND;
   int SEND_CONVERTER_NOT_FOUND;
   int SEND_NO_ACTIVE_CMIME_SERVICE_RECORD;
   int SEND_COULD_NOT_CREATE_CONNECTION;
   int SEND_CONNECTION_PENDING_CLOSURE;
   int CONNECTION_SET;
   int CONNECTION_NOT_SET;
   int CONNECTION_CLOSED_IN_RECEIVE;
}
