package net.rim.device.apps.internal.browser.css;

public interface Selector {
   short SAC_CONDITIONAL_SELECTOR;
   short SAC_ANY_NODE_SELECTOR;
   short SAC_ROOT_NODE_SELECTOR;
   short SAC_NEGATIVE_SELECTOR;
   short SAC_ELEMENT_NODE_SELECTOR;
   short SAC_TEXT_NODE_SELECTOR;
   short SAC_CDATA_SECTION_NODE_SELECTOR;
   short SAC_PROCESSING_INSTRUCTION_NODE_SELECTOR;
   short SAC_COMMENT_NODE_SELECTOR;
   short SAC_PSEUDO_ELEMENT_SELECTOR;
   short SAC_DESCENDANT_SELECTOR;
   short SAC_CHILD_SELECTOR;
   short SAC_DIRECT_ADJACENT_SELECTOR;
}
