package net.rim.device.api.hrt;

public interface HRTTypeFieldCodes {
   int TYPE_WIRELESS_NETWORK;
   int TYPE_NETWORK_NAME;
   int TYPE_LOAD_SHARING;
   int TYPE_HPID_VALUE;
   int TYPE_FST_LIST;
   int TYPE_RADIO_NETWORK_ID;
   int TYPE_HEADER_LENGTH;
   int TYPE_PRIORITY;
   int TYPE_NID_LIST;
   int TYPE_IP_LIST;
   int TYPE_APN;
   int TYPE_APN_USERNAME;
   int TYPE_APN_PASSWORD;
   int TYPE_QOS;
   int TYPE_UDP_PORT_LIST;
   int TYPE_PROTOCOL_TRANSPORT_ENCRYPTION;
   int TYPE_APPLICABLE_RADIO_TECHNOLOGY;
   int DOMAIN_ADDRESS_LIST;
   int TYPE_TRANSPORT_PROTOCOL_ID;
   int TYPE_OLD_NPC;
   int TYPE_NEW_NPC;
   int TYPE_NEW_NPC_EXTENSION;
   int TYPE_OWNING_SRID;
}
