package net.rim.device.api.hrt;

public interface HRTTypeFieldCodes {
   int TYPE_WIRELESS_NETWORK = 1;
   int TYPE_NETWORK_NAME = 2;
   int TYPE_LOAD_SHARING = 3;
   int TYPE_HPID_VALUE = 4;
   int TYPE_FST_LIST = 5;
   int TYPE_RADIO_NETWORK_ID = 6;
   int TYPE_HEADER_LENGTH = 7;
   int TYPE_PRIORITY = 8;
   int TYPE_NID_LIST = 9;
   int TYPE_IP_LIST = 16;
   int TYPE_APN = 18;
   int TYPE_APN_USERNAME = 34;
   int TYPE_APN_PASSWORD = 35;
   int TYPE_QOS = 19;
   int TYPE_UDP_PORT_LIST = 20;
   int TYPE_PROTOCOL_TRANSPORT_ENCRYPTION = 21;
   int TYPE_APPLICABLE_RADIO_TECHNOLOGY = 22;
   int DOMAIN_ADDRESS_LIST = 23;
   int TYPE_TRANSPORT_PROTOCOL_ID = 10;
   int TYPE_OLD_NPC = 11;
   int TYPE_NEW_NPC = 32;
   int TYPE_NEW_NPC_EXTENSION = 33;
   int TYPE_OWNING_SRID = 202;
}
