package net.rim.blackberry.api.mail;

public interface BodyPart$ContentType {
   String TYPE_MULTIPART;
   String TYPE_TEXT;
   String TYPE_APPLICATION;
   String TYPE_MESSAGE;
   String TYPE_IMAGE;
   String TYPE_AUDIO;
   String TYPE_VIDEO;
   String TYPE_UNKNOWN;
   String SUBTYPE_MIXED;
   String SUBTYPE_REPORT;
   String SUBTYPE_PLAIN;
   String SUBTYPE_OCTET_STREAM;
   String SUBTYPE_POSTSCRIPT;
   String SUBTYPE_DELIVERY_STATUS;
   String SUBTYPE_RFC822;
   String SUBTYPE_JPEG;
   String SUBTYPE_BASIC;
   String SUBTYPE_MPEG;
   String SUBTYPE_X_RIMDEVICE;
   String SUBTYPE_X_RIMDEVICE_ADDRESS_BOOK;
   String SUBTYPE_UNKNOWN;
   String SUBTYPE_CERTIFICATE;
   String TYPE_MULTIPART_MIXED_STRING;
   String TYPE_MULTIPART_REPORT_STRING;
   String TYPE_TEXT_PLAIN_STRING;
   String TYPE_APPLICATION_OCTET_STREAM_STRING;
   String TYPE_APPLICATION_POSTSCRIPT_STRING;
   String TYPE_MESSAGE_DELIVERY_STATUS_STRING;
   String TYPE_MESSAGE_RFC822_STRING;
   String TYPE_IMAGE_JPEG_STRING;
   String TYPE_AUDIO_BASIC_STRING;
   String TYPE_VIDEO_MPEG_STRING;
   String TYPE_UNKNOWN_UNKNOWN_STRING;
   String TYPE_ADDRESS_BOOK_STRING;
}
