package net.rim.device.apps.internal.vad.resource;

public interface VADResource {
   long BUNDLE_ID;
   String BUNDLE_NAME;
   int WHICH_NUMBER_FOR;
   int RESET_DIGITS_COMPLETE;
   int INITIALIZING;
   int NO_MATCH_FOUND;
   int NAME_PLAYBACK_VOLUME_CHOICES;
   int SENSITIVITY_CHOICES;
   int ERROR_UNKNOWN;
   int DISABLED_BY_IT_POLICY;
   int ADDRESS_BOOK_EMPTY;
   int COPYRIGHT;
   int RESET_DIGITS;
   int ADAPT_DIGITS_COMPLETE;
   int CONNECTING;
   int NAME_PLAYBACK;
   int NAME_PLAYBACK_SPEED;
   int ERROR_NO_AUDIO;
   int REBUILDING_ADDRESS_BOOK;
   int AUDIO_PROMPTS;
   int ERROR_OOM;
   int DIGIT_PLAYBACK;
   int ERROR_STARTING_CALL;
   int NAME_PLAYBACK_SPEED_CHOICES;
   int ADAPT_DIGITS;
   int ADAPT_DIGITS_INSTRUCTIONS;
   int CHOICE_LIST_CHOICES;
   int SENSITIVITY;
   int NAME_PLAYBACK_VOLUME;
   int VOICE_ACTIVATED_DIALING;
   int CHOICE_LISTS;
   int UNKNOWN;
}
