package net.rim.device.internal.resource;

public interface UIResource {
   long BUNDLE_ID;
   String BUNDLE_NAME;
   int THEME_REMOVED_MSG;
   int FONT_STYLE_MONOCHROME;
   int KEYNAME_TRACKBALL;
   int TICKET_APPLICATION_NAME;
   int KEYNAME_UP;
   int FONT_STYLE_ITALIC;
   int PLEASE_WAIT;
   int KEYNAME_VOLUME_UP;
   int MIDLET_NOTIFICATION_TEXT;
   int KEYNAME_LEFT;
   int GRAPH_FIELD_EMPTY;
   int FONT_STYLE_DOTTED_UNDERLINED;
   int LBL_PAGE;
   int KEYNAME_ALT;
   int UNABLE_TO_REMOVE_THEME_MSG;
   int TICKET_CALL_STACK;
   int KEYNAME_ESCAPE;
   int KEYNAME_VOLUME_DOWN;
   int KEYNAME_SHIFT;
   int KEYNAME_DOWN;
   int FONT_STYLE_BOLD;
   int KEYNAME_ENTER;
   int KEYNAME_SPACE;
   int THEME_REMOVED_NEXT_RESET_MSG;
   int FONT_STYLE_UNDERLINED;
   int KEYNAME_RIGHT;
   int TICKET_VENDOR;
   int KEYNAME_BACKSPACE;
   int KEYNAME_CONVENIENCE_KEY_2;
   int VOLUME_CONTROL_TEXT_RINGTONE;
   int KEYNAME_CONVENIENCE_KEY_1;
   int KEYNAME_DEL;
}
