package net.rim.device.internal.resource;

public interface UIResource {
   long BUNDLE_ID = 3711053710409943671L;
   String BUNDLE_NAME = "net.rim.device.internal.resource.UI";
   int THEME_REMOVED_MSG = 401;
   int FONT_STYLE_MONOCHROME = 22;
   int KEYNAME_TRACKBALL = 34;
   int TICKET_APPLICATION_NAME = 29;
   int KEYNAME_UP = 9;
   int FONT_STYLE_ITALIC = 20;
   int PLEASE_WAIT = 27;
   int KEYNAME_VOLUME_UP = 35;
   int MIDLET_NOTIFICATION_TEXT = 400;
   int KEYNAME_LEFT = 12;
   int GRAPH_FIELD_EMPTY = 32;
   int FONT_STYLE_DOTTED_UNDERLINED = 18;
   int LBL_PAGE = 31;
   int KEYNAME_ALT = 7;
   int UNABLE_TO_REMOVE_THEME_MSG = 403;
   int TICKET_CALL_STACK = 30;
   int KEYNAME_ESCAPE = 6;
   int KEYNAME_VOLUME_DOWN = 36;
   int KEYNAME_SHIFT = 8;
   int KEYNAME_DOWN = 11;
   int FONT_STYLE_BOLD = 19;
   int KEYNAME_ENTER = 4;
   int KEYNAME_SPACE = 2;
   int THEME_REMOVED_NEXT_RESET_MSG = 402;
   int FONT_STYLE_UNDERLINED = 21;
   int KEYNAME_RIGHT = 10;
   int TICKET_VENDOR = 28;
   int KEYNAME_BACKSPACE = 3;
   int KEYNAME_CONVENIENCE_KEY_2 = 38;
   int VOLUME_CONTROL_TEXT_RINGTONE = 33;
   int KEYNAME_CONVENIENCE_KEY_1 = 37;
   int KEYNAME_DEL = 5;
}
