package net.rim.device.api.browser.push;

public interface PushEventLogger {
   long PUSH_EVENT_LOGGER_GUID;
   String PUSH_EVENT_LOGGER_TITLE;
   int OTA_MESSAGE_RECEIVED;
   int OTA_BEFORE_DISPATCH;
   int OTA_AFTER_DISPATCH;
   int DISPATCHER_BEFORE_DECODE;
   int DISPATCHER_BEFORE_DISPATCH;
   int DISPATCHER_DETECTED_SIA;
   int DISPATCHER_AFTER_SIA;
   int DISPATCHER_BEFORE_LISTENER;
   int DISPATCHER_AFTER_LISTENER;
   int SIA_BEFORE_DECODE;
   int SIA_AFTER_DECODE;
   int SIA_BEFORE_SESSION;
   int SIA_AFTER_SESSION;
   int PUSH_PROCESSOR_ON_MESSAGE;
   int PUSH_PROCESSOR_USING_DEFAULT;
   int PUSH_PROCESSOR_ALTERNATE_APP;
   int PUSH_PROCESSOR_START_THREADS;
   int PUSH_PROCESSOR_STOP_THREADS;
   int PUSH_PROCESSOR_INVOKE_PUSH;
   int PUSH_PROCESSOR_SERVICE_BOOKS_CHANGED;
   int PUSH_PROCESSOR_START_CO;
   int PUSH_PROCESSOR_START_CL;
   int PUSH_PROCESSOR_NO_PPG_SET;
   int PUSH_PROCESSOR_NO_CONNECT_PPG;
   int PUSH_THREAD_AFTER_BACKOFF;
   int PUSH_PROCESSOR_PPG_CONNECT_START;
   int PUSH_PROCESSOR_NETWORK_STARTED;
   int PUSH_PROCESSOR_DATA_AVAILABLE;
   int PUSH_PROCESSOR_PPG_STARTING;
   int PUSH_THREAD_AWAKE_FROM_WAITING;
   int PUSH_THREAD_WAITING_FOR_DATA_NETWORK;
}
