package net.rim.device.internal.crypto.pgp;

public interface PGPSignatureSubPacketTags {
   int SIGNATURE_CREATION_TIME = 2;
   int SIGNATURE_EXPIRATION_TIME = 3;
   int EXPORTABLE_CERTIFICATION = 4;
   int TRUST_SIGNATURE = 5;
   int REGULAR_EXPRESSION = 6;
   int REVOCABLE = 7;
   int KEY_EXPIRATION_TIME = 9;
   int ADDITIONAL_DECRYPTION_KEY_FINGERPRINT = 10;
   int PREFERRED_SYMMETRIC_ALGORITHMS = 11;
   int REVOCATION_KEY = 12;
   int ISSUER_KEY_ID = 16;
   int NOTATION_DATA = 20;
   int PREFERRED_HASH_ALGORITHMS = 21;
   int PREFERRED_COMPRESSION_ALGORITHMS = 22;
   int KEY_SERVER_PREFERENCES = 23;
   int PREFERRED_KEY_SERVER = 24;
   int PRIMARY_USER_ID = 25;
   int POLICY_URL = 26;
   int KEY_FLAGS = 27;
   int SIGNERS_USER_ID = 28;
   int REASON_FOR_REVOCATION = 29;
   int FEATURES = 30;
   int REVOCATION_IDENTIFICATION = 31;
}
