package net.rim.device.internal.crypto.pgp;

public interface PGPSignatureSubPacketTags {
   int SIGNATURE_CREATION_TIME;
   int SIGNATURE_EXPIRATION_TIME;
   int EXPORTABLE_CERTIFICATION;
   int TRUST_SIGNATURE;
   int REGULAR_EXPRESSION;
   int REVOCABLE;
   int KEY_EXPIRATION_TIME;
   int ADDITIONAL_DECRYPTION_KEY_FINGERPRINT;
   int PREFERRED_SYMMETRIC_ALGORITHMS;
   int REVOCATION_KEY;
   int ISSUER_KEY_ID;
   int NOTATION_DATA;
   int PREFERRED_HASH_ALGORITHMS;
   int PREFERRED_COMPRESSION_ALGORITHMS;
   int KEY_SERVER_PREFERENCES;
   int PREFERRED_KEY_SERVER;
   int PRIMARY_USER_ID;
   int POLICY_URL;
   int KEY_FLAGS;
   int SIGNERS_USER_ID;
   int REASON_FOR_REVOCATION;
   int FEATURES;
   int REVOCATION_IDENTIFICATION;
}
