package net.rim.device.internal.crypto.pgp;

public interface PGPTags {
   int RESERVED_PACKET;
   int PUBLIC_KEY_ENCRYPTED_SESSION_KEY_PACKET;
   int SIGNATURE_PACKET;
   int SYMMETRIC_KEY_ENCRYPTED_SESSION_KEY_PACKET;
   int ONE_PASS_SIGNATURE_PACKET;
   int SECRET_KEY_PACKET;
   int PUBLIC_KEY_PACKET;
   int SECRET_SUBKEY_PACKET;
   int COMPRESSED_DATA_PACKET;
   int SYMMETRICALLY_ENCRYPTED_DATA_PACKET;
   int MARKER_PACKET;
   int LITERAL_DATA_PACKET;
   int TRUST_PACKET;
   int USER_ID_PACKET;
   int PUBLIC_SUBKEY_PACKET;
   int USER_ATTRIBUTE_PACKET;
   int SYMMETRICALLY_ENCRYPTED_INTEGRITY_PROTECTED_DATA_PACKET;
   int MODIFICATION_DETECTION_CODE_PACKET;
}
