package net.rim.device.internal.crypto.pgp;

public interface PGPTags {
   int RESERVED_PACKET = 0;
   int PUBLIC_KEY_ENCRYPTED_SESSION_KEY_PACKET = 1;
   int SIGNATURE_PACKET = 2;
   int SYMMETRIC_KEY_ENCRYPTED_SESSION_KEY_PACKET = 3;
   int ONE_PASS_SIGNATURE_PACKET = 4;
   int SECRET_KEY_PACKET = 5;
   int PUBLIC_KEY_PACKET = 6;
   int SECRET_SUBKEY_PACKET = 7;
   int COMPRESSED_DATA_PACKET = 8;
   int SYMMETRICALLY_ENCRYPTED_DATA_PACKET = 9;
   int MARKER_PACKET = 10;
   int LITERAL_DATA_PACKET = 11;
   int TRUST_PACKET = 12;
   int USER_ID_PACKET = 13;
   int PUBLIC_SUBKEY_PACKET = 14;
   int USER_ATTRIBUTE_PACKET = 17;
   int SYMMETRICALLY_ENCRYPTED_INTEGRITY_PROTECTED_DATA_PACKET = 18;
   int MODIFICATION_DETECTION_CODE_PACKET = 19;
}
