package net.rim.device.apps.internal.secureemail;

public interface StatusFieldPriorities {
   int ENCRYPTED;
   int MISSING_PRIVATE_KEY;
   int SIGNATURE_VERIFIED;
   int CERT_CHAIN_TRUSTED;
   int SIGNATURE_BES_VERIFIED;
   int CERT_CHAIN_STATUS_STALE;
   int ENCRYPTED_WEAK;
   int SIGNATURE_WEAK;
   int WORKING;
   int CANNOT_VERIFY;
   int CERT_CHAIN_UNVERIFIABLE;
   int CERT_CHAIN_UNTRUSTED;
   int CERT_CHAIN_EXPIRED;
   int CERT_CHAIN_REVOKED;
   int SIGNATURE_NO_SIGNING_CERT;
   int SIGNATURE_EMAIL_ADDRESS_NO_MATCH;
   int SIGNATURE_BES_VERIFICATION_FAILED;
   int SIGNATURE_VERIFICATION_FAILED;
   int ERROR;
   int NEED_MORE;
}
