package net.rim.device.api.itpolicy;

public interface BrowserPolicy {
   int MDS_BROWSER_TITLE = 1;
   int DISABLE_JAVASCRIPT = 2;
   int ALLOW_IBS_BROWSER = 3;
   int MDS_BROWSER_JAVASCRIPT_ENABLED = 4;
   int MDS_BROWSER_STYLESHEETS_ENABLED = 5;
   int MDS_BROWSER_HTML_TABLES_ENABLED = 6;
   int MDS_BROWSER_BSM_ENABLED = 7;
   int MORE_IMAGES_URL = 8;
   int MORE_THEMES_URL = 9;
   int MORE_TUNES_URL = 10;
   int AUTO_SYNC_DISABLED = 11;
   int MDS_BROWSER_USE_SEPARATE_ICON = 12;
   int MDS_BROWSER_DOMAINS = 13;
   int ALLOW_APP_DOWNLOAD_SERVICES = 14;
   boolean DISABLE_JAVASCRIPT_DEFAULT = false;
   boolean ALLOW_IBS_BROWSER_DEFAULT = true;
   boolean MDS_BROWSER_USE_SEPARATE_ICON_DEFAULT = false;
   boolean ALLOW_APP_DOWNLOAD_SERVICES_DEFAULT = true;
}
