package net.rim.device.api.itpolicy;

public interface BrowserPolicy {
   int MDS_BROWSER_TITLE;
   int DISABLE_JAVASCRIPT;
   int ALLOW_IBS_BROWSER;
   int MDS_BROWSER_JAVASCRIPT_ENABLED;
   int MDS_BROWSER_STYLESHEETS_ENABLED;
   int MDS_BROWSER_HTML_TABLES_ENABLED;
   int MDS_BROWSER_BSM_ENABLED;
   int MORE_IMAGES_URL;
   int MORE_THEMES_URL;
   int MORE_TUNES_URL;
   int AUTO_SYNC_DISABLED;
   int MDS_BROWSER_USE_SEPARATE_ICON;
   int MDS_BROWSER_DOMAINS;
   int ALLOW_APP_DOWNLOAD_SERVICES;
   boolean DISABLE_JAVASCRIPT_DEFAULT;
   boolean ALLOW_IBS_BROWSER_DEFAULT;
   boolean MDS_BROWSER_USE_SEPARATE_ICON_DEFAULT;
   boolean ALLOW_APP_DOWNLOAD_SERVICES_DEFAULT;
}
