package net.rim.device.api.itpolicy;

public interface CMIMEAppPolicy {
   int OTAFM_POLICY = 1;
   int ENABLE_DOCVIEWER = 2;
   int PREPEND_DISCLAIMER = 3;
   int KEEP_MESSAGE_DURATION = 4;
   int KEEP_SAVED_MESSAGE_DURATION = 5;
   int MAX_NATIVE_ATTACHMENT_MFH_TOTAL_SIZE = 6;
   int MAX_NATIVE_ATTACHMENT_MFH_SIZE = 7;
   int ALLOW_AUTO_ATTACHMENT_DOWNLOAD = 8;
   int DISABLE_NOTES_NATIVE_ENCRYPTION_FORWARD_AND_REPLY = 9;
   int NOTES_NATIVE_ENCRYPTION_PASSWORD_TIMEOUT = 10;
}
