package net.rim.device.api.itpolicy;

public interface CMIMEAppPolicy {
   int OTAFM_POLICY;
   int ENABLE_DOCVIEWER;
   int PREPEND_DISCLAIMER;
   int KEEP_MESSAGE_DURATION;
   int KEEP_SAVED_MESSAGE_DURATION;
   int MAX_NATIVE_ATTACHMENT_MFH_TOTAL_SIZE;
   int MAX_NATIVE_ATTACHMENT_MFH_SIZE;
   int ALLOW_AUTO_ATTACHMENT_DOWNLOAD;
   int DISABLE_NOTES_NATIVE_ENCRYPTION_FORWARD_AND_REPLY;
   int NOTES_NATIVE_ENCRYPTION_PASSWORD_TIMEOUT;
}
