package net.rim.device.api.itpolicy;

public interface EnterpriseVoiceClientPolicy {
   int PROPERTY_ENTERPRISE_VOICE_CLIENT_POLICY_GROUP;
   int DISABLE_ENTERPRISE_VOICE_CLIENT;
   int REJECT_NON_ENTERPRISE_VOICE_CALLS;
   int LOCK_OUTGOING_LINE;
   boolean DEFAULT_PROPERTY_DISABLE_ENTERPRISE_VOICE_CLIENT;
   boolean DEFAULT_PROPERTY_REJECT_NON_ENTERPRISE_VOICE_CALLS;
   boolean DEFAULT_PROPERTY_LOCK_OUTGOING_LINE;
}
