package net.rim.device.api.itpolicy;

public interface EnterpriseVoiceClientPolicy {
   int PROPERTY_ENTERPRISE_VOICE_CLIENT_POLICY_GROUP = 0;
   int DISABLE_ENTERPRISE_VOICE_CLIENT = 1;
   int REJECT_NON_ENTERPRISE_VOICE_CALLS = 2;
   int LOCK_OUTGOING_LINE = 3;
   boolean DEFAULT_PROPERTY_DISABLE_ENTERPRISE_VOICE_CLIENT = false;
   boolean DEFAULT_PROPERTY_REJECT_NON_ENTERPRISE_VOICE_CALLS = false;
   boolean DEFAULT_PROPERTY_LOCK_OUTGOING_LINE = false;
}
