package net.rim.device.api.itpolicy;

public interface MDSPolicy {
   int MDS_POLICY;
   int DISABLE_MDS_RE;
   int SECURITY_MIN_VERSION;
   int SECURITY_VERIFY_CERTIFICATE;
   int DISABLE_PUBLIC_MDSS;
   int DISABLE_USER_INITIATED_ACTIVATION;
   boolean DISABLE_MDS_RE_DEFAULT;
   int SECURITY_MIN_VERSION_DEFAULT;
   boolean SECURITY_VERIFY_CERTIFICATE_DEFAULT;
   boolean DISABLE_PUBLIC_MDSS_DEFAULT;
   boolean DISABLE_USER_INITIATED_ACTIVATION_DEFAULT;
}
