package net.rim.device.api.itpolicy;

public interface OTAUpgradePolicy {
   int ALLOW_NON_BES_UPGRADE;
   int DISALLOW_DEVICE_USER_REQUESTED_UPGRADE;
   int DISALLOW_DEVICE_USER_REQUESTED_ROLLBACK;
   int DISALLOW_PATCH_DOWNLOAD_OVER_WAN;
   int DISALLOW_PATCH_DOWNLOAD_OVER_ROAMING_WAN;
   int DISALLOW_PATCH_DOWNLOAD_OVER_INTERNATIONAL_ROAMING_WAN;
   int DISALLOW_PATCH_DOWNLOAD_OVER_WIFI;
}
