package net.rim.device.api.itpolicy;

public interface OTAUpgradePolicy {
   int ALLOW_NON_BES_UPGRADE = 1;
   int DISALLOW_DEVICE_USER_REQUESTED_UPGRADE = 2;
   int DISALLOW_DEVICE_USER_REQUESTED_ROLLBACK = 3;
   int DISALLOW_PATCH_DOWNLOAD_OVER_WAN = 4;
   int DISALLOW_PATCH_DOWNLOAD_OVER_ROAMING_WAN = 5;
   int DISALLOW_PATCH_DOWNLOAD_OVER_INTERNATIONAL_ROAMING_WAN = 6;
   int DISALLOW_PATCH_DOWNLOAD_OVER_WIFI = 7;
}
