package net.rim.device.api.itpolicy;

public interface PasswordPolicy {
   int PASSWORD_TIMEOUT;
   int PASSWORD_MAX_ATTEMPTS;
   int SUPPRESS_PASSWORD_ECHO;
   int PASSWORD_HISTORY;
   int DURESS_PASSWORD_ENABLE;
   int DURESS_PASSWORD_EXTENSION;
   int DURESS_NOTIFICATION;
   int PERIODIC_CHALLENGE_TIMEOUT;
   int FORBIDDEN_PASSWORDS;
   int PASSWORD_MAX_ATTEMPTS_DEFAULT;
   int PASSWORD_TIMEOUT_DEFAULT;
   boolean SUPPRESS_PASSWORD_ECHO_DEFAULT;
   int PERIODIC_CHALLENGE_TIMEOUT_DEFAULT;
   int PASSWORD_HISTORY_DEFAULT;
}
