package net.rim.device.api.itpolicy;

public interface PasswordPolicy {
   int PASSWORD_TIMEOUT = 1;
   int PASSWORD_MAX_ATTEMPTS = 2;
   int SUPPRESS_PASSWORD_ECHO = 3;
   int PASSWORD_HISTORY = 4;
   int DURESS_PASSWORD_ENABLE = 5;
   int DURESS_PASSWORD_EXTENSION = 6;
   int DURESS_NOTIFICATION = 7;
   int PERIODIC_CHALLENGE_TIMEOUT = 8;
   int FORBIDDEN_PASSWORDS = 9;
   int PASSWORD_MAX_ATTEMPTS_DEFAULT = 10;
   int PASSWORD_TIMEOUT_DEFAULT = 60000;
   boolean SUPPRESS_PASSWORD_ECHO_DEFAULT = false;
   int PERIODIC_CHALLENGE_TIMEOUT_DEFAULT = 60;
   int PASSWORD_HISTORY_DEFAULT = 0;
}
