package net.rim.device.api.itpolicy;

public interface SyncPolicy {
   int DISABLE_ALL_WIRELESS_SYNC;
   int DISABLE_ADDRESS_WIRELESS_SYNC;
   int DISABLE_CALENDAR_WIRELESS_SYNC;
   int DISABLE_MEMOPAD_WIRELESS_SYNC;
   int DISABLE_TASKS_WIRELESS_SYNC;
   int FORCE_INIT_THROUGH_OTA_BY_PASS;
   int DISABLE_PIN_MESSAGES_WIRELESS_SYNC;
   int DISABLE_SMS_MESSAGES_WIRELESS_SYNC;
   int DISABLE_PHONE_CALL_LOG_WIRELESS_SYNC;
   int DISABLE_EA_PROGRESS;
   boolean DISABLE_ALL_WIRELESS_SYNC_DEFAULT;
   boolean DISABLE_ADDRESS_WIRELESS_SYNC_DEFAULT;
   boolean DISABLE_CALENDAR_WIRELESS_SYNC_DEFAULT;
   boolean DISABLE_MEMOPAD_WIRELESS_SYNC_DEFAULT;
   boolean DISABLE_TASKS_WIRELESS_SYNC_DEFAULT;
   boolean DISABLE_PIN_MESSAGES_WIRELESS_SYNC_DEFAULT;
   boolean DISABLE_SMS_MESSAGES_WIRELESS_SYNC_DEFAULT;
   boolean DISABLE_PHONE_CALL_LOG_WIRELESS_SYNC_DEFAULT;
   boolean DISABLE_EA_PROGRESS_DEFAULT;
}
