package net.rim.device.api.itpolicy;

public interface SyncPolicy {
   int DISABLE_ALL_WIRELESS_SYNC = 1;
   int DISABLE_ADDRESS_WIRELESS_SYNC = 2;
   int DISABLE_CALENDAR_WIRELESS_SYNC = 3;
   int DISABLE_MEMOPAD_WIRELESS_SYNC = 4;
   int DISABLE_TASKS_WIRELESS_SYNC = 5;
   int FORCE_INIT_THROUGH_OTA_BY_PASS = 6;
   int DISABLE_PIN_MESSAGES_WIRELESS_SYNC = 7;
   int DISABLE_SMS_MESSAGES_WIRELESS_SYNC = 8;
   int DISABLE_PHONE_CALL_LOG_WIRELESS_SYNC = 9;
   int DISABLE_EA_PROGRESS = 10;
   boolean DISABLE_ALL_WIRELESS_SYNC_DEFAULT = false;
   boolean DISABLE_ADDRESS_WIRELESS_SYNC_DEFAULT = false;
   boolean DISABLE_CALENDAR_WIRELESS_SYNC_DEFAULT = false;
   boolean DISABLE_MEMOPAD_WIRELESS_SYNC_DEFAULT = false;
   boolean DISABLE_TASKS_WIRELESS_SYNC_DEFAULT = false;
   boolean DISABLE_PIN_MESSAGES_WIRELESS_SYNC_DEFAULT = true;
   boolean DISABLE_SMS_MESSAGES_WIRELESS_SYNC_DEFAULT = true;
   boolean DISABLE_PHONE_CALL_LOG_WIRELESS_SYNC_DEFAULT = false;
   boolean DISABLE_EA_PROGRESS_DEFAULT = false;
}
