package net.rim.device.api.itpolicy;

public interface TCPITPolicy {
   int TCP_ITP_TAG_RESET = 2;
   int TCP_ITP_TAG_USER_OVERRIDE = 3;
   int TCP_ITP_TAG_APN = 4;
   int TCP_ITP_TAG_USERNAME = 5;
   int TCP_ITP_TAG_PASSWORD = 6;
   int TCP_ITP_TAG_OUTGOING_TCP_ENABLED = 7;
   int TCP_ITP_TAG_TCP_SERVER_SOCKETS_ENABLED = 8;
   boolean TCP_OPTIONS_DEFAULT_USEREDITABLE = true;
   boolean TCP_OPTIONS_DEFAULT_OUTGOING_TCP_ENABLED = true;
   boolean TCP_OPTIONS_DEFAULT_TCP_SERVER_SOCKETS_ENABLED = true;
}
