package net.rim.device.api.itpolicy;

public interface TCPITPolicy {
   int TCP_ITP_TAG_RESET;
   int TCP_ITP_TAG_USER_OVERRIDE;
   int TCP_ITP_TAG_APN;
   int TCP_ITP_TAG_USERNAME;
   int TCP_ITP_TAG_PASSWORD;
   int TCP_ITP_TAG_OUTGOING_TCP_ENABLED;
   int TCP_ITP_TAG_TCP_SERVER_SOCKETS_ENABLED;
   boolean TCP_OPTIONS_DEFAULT_USEREDITABLE;
   boolean TCP_OPTIONS_DEFAULT_OUTGOING_TCP_ENABLED;
   boolean TCP_OPTIONS_DEFAULT_TCP_SERVER_SOCKETS_ENABLED;
}
