package net.rim.device.api.itpolicy;

public interface TLSPolicy {
   int TLS_DISABLE_WEAK_CIPHERS = 1;
   int TLS_DISABLE_UNTRUSTED_CONNECTION = 2;
   int TLS_MIN_STRONG_RSA_KEY_LENGTH = 3;
   int TLS_MIN_STRONG_DH_KEY_LENGTH = 4;
   int TLS_MIN_STRONG_ECC_KEY_LENGTH = 5;
   int TLS_DISABLE_INVALID_CONNECTION = 6;
   int TLS_RESTRICT_FIPS_CIPHERS = 7;
   int TLS_MIN_STRONG_DSA_KEY_LENGTH = 8;
   int TLS_DEVICE_SIDE_ONLY = 9;
   int TLS_DISABLE_WEAK_CIPHERS_DEFAULT = 2;
   int TLS_DISABLE_UNTRUSTED_CONNECTION_DEFAULT = 1;
   int TLS_MIN_STRONG_RSA_KEY_LENGTH_DEFAULT = 512;
   int TLS_MIN_STRONG_DH_KEY_LENGTH_DEFAULT = 512;
   int TLS_MIN_STRONG_ECC_KEY_LENGTH_DEFAULT = 160;
   int TLS_DISABLE_INVALID_CONNECTION_DEFAULT = 2;
   boolean TLS_RESTRICT_FIPS_CIPHERS_DEFAULT = false;
   int TLS_MIN_STRONG_DSA_KEY_LENGTH_DEFAULT = 512;
   boolean TLS_DEVICE_SIDE_ONLY_DEFAULT = false;
}
