package net.rim.device.api.itpolicy;

public interface TLSPolicy {
   int TLS_DISABLE_WEAK_CIPHERS;
   int TLS_DISABLE_UNTRUSTED_CONNECTION;
   int TLS_MIN_STRONG_RSA_KEY_LENGTH;
   int TLS_MIN_STRONG_DH_KEY_LENGTH;
   int TLS_MIN_STRONG_ECC_KEY_LENGTH;
   int TLS_DISABLE_INVALID_CONNECTION;
   int TLS_RESTRICT_FIPS_CIPHERS;
   int TLS_MIN_STRONG_DSA_KEY_LENGTH;
   int TLS_DEVICE_SIDE_ONLY;
   int TLS_DISABLE_WEAK_CIPHERS_DEFAULT;
   int TLS_DISABLE_UNTRUSTED_CONNECTION_DEFAULT;
   int TLS_MIN_STRONG_RSA_KEY_LENGTH_DEFAULT;
   int TLS_MIN_STRONG_DH_KEY_LENGTH_DEFAULT;
   int TLS_MIN_STRONG_ECC_KEY_LENGTH_DEFAULT;
   int TLS_DISABLE_INVALID_CONNECTION_DEFAULT;
   boolean TLS_RESTRICT_FIPS_CIPHERS_DEFAULT;
   int TLS_MIN_STRONG_DSA_KEY_LENGTH_DEFAULT;
   boolean TLS_DEVICE_SIDE_ONLY_DEFAULT;
}
