package net.rim.device.api.itpolicy;

public interface WTLSPolicy {
   int WTLS_DISABLE_WEAK_CIPHERS = 1;
   int WTLS_DISABLE_UNTRUSTED_CONNECTION = 2;
   int WTLS_MIN_STRONG_RSA_KEY_LENGTH = 3;
   int WTLS_MIN_STRONG_DH_KEY_LENGTH = 4;
   int WTLS_MIN_STRONG_ECC_KEY_LENGTH = 5;
   int WTLS_DISABLE_INVALID_CONNECTION = 6;
   int WTLS_RESTRICT_FIPS_CIPHERS = 7;
   int WTLS_DISABLE_WEAK_CIPHERS_DEFAULT = 2;
   int WTLS_DISABLE_UNTRUSTED_CONNECTION_DEFAULT = 2;
   int WTLS_MIN_STRONG_RSA_KEY_LENGTH_DEFAULT = 512;
   int WTLS_MIN_STRONG_DH_KEY_LENGTH_DEFAULT = 512;
   int WTLS_MIN_STRONG_ECC_KEY_LENGTH_DEFAULT = 160;
   int WTLS_DISABLE_INVALID_CONNECTION_DEFAULT = 2;
   boolean WTLS_RESTRICT_FIPS_CIPHERS_DEFAULT = false;
}
