package net.rim.device.api.itpolicy;

public interface WTLSPolicy {
   int WTLS_DISABLE_WEAK_CIPHERS;
   int WTLS_DISABLE_UNTRUSTED_CONNECTION;
   int WTLS_MIN_STRONG_RSA_KEY_LENGTH;
   int WTLS_MIN_STRONG_DH_KEY_LENGTH;
   int WTLS_MIN_STRONG_ECC_KEY_LENGTH;
   int WTLS_DISABLE_INVALID_CONNECTION;
   int WTLS_RESTRICT_FIPS_CIPHERS;
   int WTLS_DISABLE_WEAK_CIPHERS_DEFAULT;
   int WTLS_DISABLE_UNTRUSTED_CONNECTION_DEFAULT;
   int WTLS_MIN_STRONG_RSA_KEY_LENGTH_DEFAULT;
   int WTLS_MIN_STRONG_DH_KEY_LENGTH_DEFAULT;
   int WTLS_MIN_STRONG_ECC_KEY_LENGTH_DEFAULT;
   int WTLS_DISABLE_INVALID_CONNECTION_DEFAULT;
   boolean WTLS_RESTRICT_FIPS_CIPHERS_DEFAULT;
}
