package net.rim.tools.compiler.vm;

public interface Constants extends VMConfig {
   int EOF = -1;
   int SIZE_UNKNOWN = -1;
   int ADDRESS_UNKNOWN = -1;
   int OFFSET_UNKNOWN = -1;
   int ORDINAL_UNKNOWN = -1;
   int ADDRESS_NULL = 65535;
   int OFFSET_NULL = 65535;
   int MODULE_NULL = 255;
   int FOREIGN_ORDINAL_MARKER = 2;
   int FAKE_OFFSET_ADJUST = 65536;
   int IsExported = 65536;
   char[] HEXCHARS;
   int DOUBLE_SIZE = 8;
   int FLOAT_SIZE = 4;
   int LONG_SIZE = 8;
   int INTEGER_SIZE = 4;
   int REF_SIZE = 4;
   int SHORT_SIZE = 2;
   int CHAR_SIZE = 2;
   int BYTE_SIZE = 1;
   int BOOLEAN_SIZE = 1;
   int VOID_SIZE = 0;
   int OPCODE_SIZE = 1;
   int WORD_COUNT = 1;
   int LONG_COUNT = 2;
   int DOUBLE_COUNT = 2;
   int BYTE_MASK = 255;
   int SHORT_MASK = 65535;
   int BYTE_SHIFT = 8;
   int BYTE_SHIFT2 = 16;
   int BYTE_SHIFT3 = 24;
   int BYTE_SHIFT4 = 32;
   int BYTE_SHIFT5 = 40;
   int BYTE_SHIFT6 = 48;
   int BYTE_SHIFT7 = 56;
   int INTEGER_SHIFT = 32;
   int BUFFER_SIZE = 256;
   int MAX_SECTION_SIZE = 65000;
   int MAX_ARRAY_NESTING = 255;
   int MAX_PARM_COUNT = 255;
   int MAX_SECURE_INDEX = 255;
   int MAX_INC_OFFSET = 128;
   int MAX_INC_INDEX = 255;
   int MAX_QUICK_INDEX = 7;
   int MAX_FIELD = 255;
   int MAX_WIDE_FIELD = 511;
   int FIELD_WIDE_OFFSET = 256;
   int MAX_SHORT_BRANCH = 128;
   int MAX_LONG_BRANCH = 32768;
   int MAX_MODULE_NAME_SIZE = 128;
   int MAX_TYPELIST_RLE = 15;
}
