package net.rim.device.apps.internal.bis.launch.resource;

public interface BISLaunchResource {
   long BUNDLE_ID;
   String BUNDLE_NAME;
   int STATUS_APP_UPDATE_SUCCESS;
   int BUTTON_LABEL_UPDATE_NOW;
   int CHOICE_RESTART_LATER;
   int SCREEN_TITLE_UPDATES;
   int CHOICE_RUN;
   int APP_TITLE;
   int ERROR_IO;
   int STATUS_APP_UPDATE_FAILED;
   int CHOICE_RESTART;
   int LABEL_NEW_MANDATORY_UPDATE;
   int STATUS_APP_UPDATE_NO_MEMORY;
   int STATUS_DOWNLOAD;
   int BUTTON_LABEL_CLOSE;
   int STATUS_APP_UPDATE_CANCELLED;
   int LABEL_UPGRADE_RESTART;
   int CHOICE_OK;
   int SCREEN_TITLE_INITIALIZATION;
   int STATUS_PROCESSING;
   int BUTTON_LABEL_UPDATE_LATER;
   int LABEL_NEW_VERSION_AVAILABLE;
   int STATUS_APP_UPDATE_REBOOT;
}
