package net.rim.device.apps.internal.bis.config;

import java.util.Vector;
import net.rim.device.apps.internal.bis.api.ui.ApplicationController;
import net.rim.device.apps.internal.bis.commands.AcceptPinChangeCommand;
import net.rim.device.apps.internal.bis.commands.AccountSetupCommand;
import net.rim.device.apps.internal.bis.commands.AddFilterCommand;
import net.rim.device.apps.internal.bis.commands.AddressBookSetupCommand;
import net.rim.device.apps.internal.bis.commands.AdvancedEditCommand;
import net.rim.device.apps.internal.bis.commands.CalendarSetupCommand;
import net.rim.device.apps.internal.bis.commands.ChangeDeviceCommand;
import net.rim.device.apps.internal.bis.commands.ChangeLanguageCommand;
import net.rim.device.apps.internal.bis.commands.ChangePasswordCommand;
import net.rim.device.apps.internal.bis.commands.DeleteCommand;
import net.rim.device.apps.internal.bis.commands.DeleteExecuteCommand;
import net.rim.device.apps.internal.bis.commands.DeleteFilterCommand;
import net.rim.device.apps.internal.bis.commands.DeleteFilterExecuteCommand;
import net.rim.device.apps.internal.bis.commands.EditCommand;
import net.rim.device.apps.internal.bis.commands.EditFilterCommand;
import net.rim.device.apps.internal.bis.commands.EditSaveCommand;
import net.rim.device.apps.internal.bis.commands.EndUserAgreementCommand;
import net.rim.device.apps.internal.bis.commands.ExistingEmailSetupCommand;
import net.rim.device.apps.internal.bis.commands.FilterSummaryCommand;
import net.rim.device.apps.internal.bis.commands.ForgotHostedPasswordCommand;
import net.rim.device.apps.internal.bis.commands.ForgotPasswordCommand;
import net.rim.device.apps.internal.bis.commands.HostedEmailSetupCommand;
import net.rim.device.apps.internal.bis.commands.ISPEmailSetupCommand;
import net.rim.device.apps.internal.bis.commands.InitializationCommand;
import net.rim.device.apps.internal.bis.commands.LoginCommand;
import net.rim.device.apps.internal.bis.commands.OWAEmailSetupCommand;
import net.rim.device.apps.internal.bis.commands.SendSBCommand;
import net.rim.device.apps.internal.bis.commands.UsernameSetupCommand;
import net.rim.device.apps.internal.bis.commands.ValidateCommand;
import net.rim.device.apps.internal.bis.commands.ValidatePasswordCommand;
import net.rim.device.apps.internal.bis.commands.ValidateSkipCommand;
import net.rim.device.apps.internal.bis.ui.AOLTermsOfServicesScreen;
import net.rim.device.apps.internal.bis.ui.AccountServicesConfirmationScreen;
import net.rim.device.apps.internal.bis.ui.AccountSetupConfirmationMainScreen;
import net.rim.device.apps.internal.bis.ui.AccountSetupConfirmationScreen;
import net.rim.device.apps.internal.bis.ui.AccountSetupInstructionScreen;
import net.rim.device.apps.internal.bis.ui.AccountSetupScreen;
import net.rim.device.apps.internal.bis.ui.AccountSetupSuggestionsScreen;
import net.rim.device.apps.internal.bis.ui.AddExchangeEmail;
import net.rim.device.apps.internal.bis.ui.AddFilterScreen;
import net.rim.device.apps.internal.bis.ui.AddISPEmailScreen;
import net.rim.device.apps.internal.bis.ui.AdditionalInformationRequiredScreen;
import net.rim.device.apps.internal.bis.ui.AddressBookSetupScreen;
import net.rim.device.apps.internal.bis.ui.AdvancedEditScreen;
import net.rim.device.apps.internal.bis.ui.CalendarSetupScreen;
import net.rim.device.apps.internal.bis.ui.CannotContinueScreen;
import net.rim.device.apps.internal.bis.ui.ChangeDeviceScreen;
import net.rim.device.apps.internal.bis.ui.ChangeLanguageScreen;
import net.rim.device.apps.internal.bis.ui.ChangePasswordScreen;
import net.rim.device.apps.internal.bis.ui.ClosingScreen;
import net.rim.device.apps.internal.bis.ui.DeleteConfirmationScreen;
import net.rim.device.apps.internal.bis.ui.DeleteFilterConfirmationScreen;
import net.rim.device.apps.internal.bis.ui.DeviceNotRegisteredScreen;
import net.rim.device.apps.internal.bis.ui.DisagreeEndUserAgreementCommand;
import net.rim.device.apps.internal.bis.ui.EditFilterScreen;
import net.rim.device.apps.internal.bis.ui.EmailSetupScreen;
import net.rim.device.apps.internal.bis.ui.EndUserAgreementContentScreen;
import net.rim.device.apps.internal.bis.ui.EndUserAgreementScreen;
import net.rim.device.apps.internal.bis.ui.ExistingEmailSetupScreen;
import net.rim.device.apps.internal.bis.ui.FilterConfirmationScreen;
import net.rim.device.apps.internal.bis.ui.FiltersSummaryScreen;
import net.rim.device.apps.internal.bis.ui.ForgotHostedPasswordScreen;
import net.rim.device.apps.internal.bis.ui.ForgotPasswordScreen;
import net.rim.device.apps.internal.bis.ui.GeneralSettingsEditScreen;
import net.rim.device.apps.internal.bis.ui.HostedAccountEditScreen;
import net.rim.device.apps.internal.bis.ui.HostedChangePasswordScreen;
import net.rim.device.apps.internal.bis.ui.HostedSecretQuestionScreen;
import net.rim.device.apps.internal.bis.ui.HotmailPRVErrorScreen;
import net.rim.device.apps.internal.bis.ui.InitializationFailedScreen;
import net.rim.device.apps.internal.bis.ui.LoginScreen;
import net.rim.device.apps.internal.bis.ui.MailConnectorScreen;
import net.rim.device.apps.internal.bis.ui.NewBBEmailAddressScreen;
import net.rim.device.apps.internal.bis.ui.OWAAdvancedEditScreen;
import net.rim.device.apps.internal.bis.ui.PasswordValidationScreen;
import net.rim.device.apps.internal.bis.ui.PinChangeDetectedScreen;
import net.rim.device.apps.internal.bis.ui.ProprietaryAccountEditScreen;
import net.rim.device.apps.internal.bis.ui.SMCAccountEditScreen;
import net.rim.device.apps.internal.bis.ui.SelectAccountTypeScreen;
import net.rim.device.apps.internal.bis.ui.ServiceBooksScreen;
import net.rim.device.apps.internal.bis.ui.ServicesMainScreen;
import net.rim.device.apps.internal.bis.ui.SetupPersonalEmailScreen;
import net.rim.device.apps.internal.bis.ui.SetupWorkEmailScreen;
import net.rim.device.apps.internal.bis.ui.UsernameCreatedEmailScreen;
import net.rim.device.apps.internal.bis.ui.UsernameSetupScreen;

public final class UINavigationConfig {
   public static final Vector loadStandardConfig(int uiMode) {
      ApplicationController appController = ApplicationController.getInstance();
      Vector shutdownListeners = new Vector();
      LoginScreen loginScreen = new LoginScreen();
      appController.registerLinkView(0, loginScreen);
      shutdownListeners.addElement(loginScreen);
      appController.registerLinkView(1, new AccountSetupScreen());
      appController.registerLinkView(2, new ForgotPasswordScreen());
      appController.registerLinkView(3, new EmailSetupScreen());
      appController.registerLinkView(4, new ExistingEmailSetupScreen());
      appController.registerLinkView(5, new NewBBEmailAddressScreen());
      appController.registerLinkView(7, new ServicesMainScreen());
      appController.registerLinkView(8, new EndUserAgreementScreen());
      appController.registerLinkView(9, new EndUserAgreementContentScreen(false));
      appController.registerLinkView(10, new InitializationFailedScreen());
      appController.registerLinkView(11, new ChangeLanguageScreen());
      appController.registerLinkView(12, new ProprietaryAccountEditScreen());
      appController.registerLinkView(13, new HostedAccountEditScreen());
      appController.registerLinkView(14, new AccountSetupSuggestionsScreen());
      appController.registerLinkView(15, new AdditionalInformationRequiredScreen());
      appController.registerLinkView(16, new SelectAccountTypeScreen());
      appController.registerLinkView(17, new AOLTermsOfServicesScreen());
      appController.registerLinkView(18, new HotmailPRVErrorScreen());
      appController.registerLinkView(19, new SetupPersonalEmailScreen());
      appController.registerLinkView(20, new SetupWorkEmailScreen());
      appController.registerLinkView(21, new MailConnectorScreen());
      appController.registerLinkView(22, new AddExchangeEmail());
      appController.registerLinkView(23, new AddISPEmailScreen());
      appController.registerLinkView(24, new AccountSetupInstructionScreen());
      appController.registerLinkView(25, new GeneralSettingsEditScreen());
      appController.registerLinkView(26, new DeleteConfirmationScreen());
      appController.registerLinkView(30, new AccountSetupConfirmationScreen());
      appController.registerLinkView(31, new AccountSetupConfirmationMainScreen());
      appController.registerLinkView(28, new ChangePasswordScreen());
      appController.registerLinkView(29, new ServiceBooksScreen());
      appController.registerLinkView(27, new ChangeDeviceScreen());
      appController.registerLinkView(32, new PinChangeDetectedScreen());
      appController.registerLinkView(35, new OWAAdvancedEditScreen());
      appController.registerLinkView(36, new AdvancedEditScreen());
      appController.registerLinkView(37, new CannotContinueScreen());
      appController.registerLinkView(39, new ClosingScreen(true));
      appController.registerLinkView(40, new ClosingScreen(false));
      appController.registerLinkView(38, new SMCAccountEditScreen());
      appController.registerLinkView(41, new EndUserAgreementContentScreen(true));
      appController.registerLinkView(43, new FiltersSummaryScreen());
      appController.registerLinkView(46, new AddFilterScreen());
      appController.registerLinkView(47, new EditFilterScreen());
      appController.registerLinkView(44, new DeleteFilterConfirmationScreen());
      appController.registerLinkView(45, new FilterConfirmationScreen());
      appController.registerLinkView(47, new EditFilterScreen());
      appController.registerLinkView(48, new PasswordValidationScreen());
      appController.registerLinkView(49, new UsernameSetupScreen());
      appController.registerLinkView(50, new ForgotHostedPasswordScreen());
      appController.registerLinkView(51, new HostedSecretQuestionScreen());
      appController.registerLinkView(52, new HostedChangePasswordScreen());
      appController.registerLinkView(53, new DeviceNotRegisteredScreen());
      appController.registerLinkView(54, new UsernameCreatedEmailScreen());
      appController.registerLinkView(55, new AddressBookSetupScreen());
      appController.registerLinkView(56, new CalendarSetupScreen());
      appController.registerLinkView(57, new AccountServicesConfirmationScreen());
      appController.registerGlobalView("error", 37);
      appController.registerGlobalView("notAuthorized", 0);
      appController.registerCommand(0, new InitializationCommand());
      appController.registerViewForward(0, "success", 0);
      appController.registerViewForward(0, "promptLogin", 0);
      appController.registerViewForward(0, "autoLogin", 0);
      appController.registerViewForward(0, "failedLoginCred", 0);
      appController.registerViewForward(0, "failedSessionNoLogin", 0);
      appController.registerViewForward(0, "failed", 10);
      appController.registerViewForward(0, "tmobileSSOSuccess", 7);
      appController.registerViewForward(0, "tmobileSSOFailed", 10);
      appController.registerViewForward(0, "tmobileAccountSuspended", 40);
      appController.registerViewForward(0, "tmobileDeviceSuspended", 40);
      appController.registerViewForward(0, "tmobileDeviceInUse", 40);
      appController.registerViewForward(0, "termsNotAccepted", 8);
      appController.registerViewForward(0, "pinChangeDetected", 32);
      appController.registerViewForward(0, "autoAuthSuccess", 7);
      appController.registerViewForward(0, "autoAuthFailed", 53);
      appController.registerViewForward(0, "autoAuthHostedSecretQuestion", 51);
      appController.registerViewForward(0, "autoAuthBBMailCreateHosted", 5);
      appController.registerCommand(1, new LoginCommand());
      appController.registerViewForward(1, "success", 7);
      appController.registerViewForward(1, "termsNotAccepted", 8);
      appController.registerViewForward(1, "pinChangeDetected", 32);
      appController.registerViewForward(1, "failed", 0);
      appController.registerCommand(2, new ExistingEmailSetupCommand());
      appController.registerViewForward(2, "success", 30);
      appController.registerViewForward(2, "reenter", 15);
      appController.registerViewForward(2, "selectAccount", 16);
      appController.registerViewForward(2, "promptAOLTerms", 17);
      appController.registerViewForward(2, "promptHotmailError", 18);
      appController.registerViewForward(2, "failed", 3);
      appController.registerCommand(3, new HostedEmailSetupCommand());
      appController.registerViewForward(3, "success", 30);
      appController.registerViewForward(3, "showHostedMailSuggestions", 5);
      appController.registerViewForward(3, "failed", 5);
      appController.registerCommand(4, new OWAEmailSetupCommand());
      appController.registerViewForward(4, "success", 30);
      appController.registerViewForward(4, "failed", 22);
      appController.registerCommand(5, new AccountSetupCommand());
      appController.registerViewForward(5, "success", 3);
      appController.registerViewForward(5, "successBBMail", 30);
      appController.registerViewForward(5, "showAccountSuggestions", 14);
      appController.registerViewForward(5, "deviceInUse", 0);
      appController.registerCommand(6, new ChangeLanguageCommand());
      appController.registerViewForward(6, "success", 7);
      appController.registerViewForward(6, "failed", 11);
      appController.registerCommand(18, new ChangePasswordCommand());
      appController.registerViewForward(18, "success", 7);
      appController.registerViewForward(18, "failed", 28);
      appController.registerCommand(7, new EditCommand());
      appController.registerViewForward(7, "editProprietary", 12);
      appController.registerViewForward(7, "editHosted", 13);
      appController.registerViewForward(7, "editISP", 25);
      appController.registerViewForward(7, "editOWA", 25);
      appController.registerViewForward(7, "editSMC", 38);
      appController.registerCommand(8, new EditSaveCommand());
      appController.registerViewForward(8, "success", 7);
      appController.registerViewForward(8, "failed", 7);
      appController.registerViewForward(8, "passwordValidation", 48);
      appController.registerViewForward(8, "validationFailed", 48);
      appController.registerViewForward(8, "hostedValidationFailed", 48);
      appController.registerCommand(9, new DeleteCommand());
      appController.registerViewForward(9, "success", 26);
      appController.registerCommand(10, new DeleteExecuteCommand());
      appController.registerViewForward(10, "success", 7);
      appController.registerViewForward(10, "failed", 7);
      appController.registerCommand(24, new FilterSummaryCommand());
      appController.registerViewForward(24, "success", 43);
      appController.registerCommand(26, new DeleteFilterCommand());
      appController.registerViewForward(26, "success", 44);
      appController.registerCommand(25, new DeleteFilterExecuteCommand());
      appController.registerViewForward(25, "success", 43);
      appController.registerViewForward(25, "failed", 43);
      appController.registerCommand(27, new AddFilterCommand());
      appController.registerViewForward(27, "success", 43);
      appController.registerViewForward(27, "failed", 46);
      appController.registerViewForward(27, "confirm", 45);
      appController.registerCommand(28, new EditFilterCommand());
      appController.registerViewForward(28, "success", 47);
      appController.registerCommand(11, new ForgotPasswordCommand());
      appController.registerViewForward(11, "success", 0);
      appController.registerViewForward(11, "failed", 2);
      appController.registerCommand(14, new SendSBCommand());
      appController.registerViewForward(14, "success", 7);
      appController.registerViewForward(14, "failed", 29);
      appController.registerCommand(12, new ISPEmailSetupCommand());
      appController.registerViewForward(12, "success", 30);
      appController.registerCommand(15, new EndUserAgreementCommand(false));
      appController.registerViewForward(15, "success", 9);
      appController.registerCommand(23, new EndUserAgreementCommand(false));
      appController.registerViewForward(23, "success", 41);
      appController.registerCommand(17, new ChangeDeviceCommand());
      appController.registerViewForward(17, "success", 7);
      appController.registerViewForward(17, "failed", 27);
      appController.registerViewForward(17, "autoAuthSuccess", 48);
      appController.registerCommand(16, new EndUserAgreementCommand(true));
      appController.registerViewForward(16, "success", 1);
      appController.registerViewForward(16, "acceptLogin", 7);
      appController.registerViewForward(16, "autoAuthSuccess", 3);
      appController.registerViewForward(16, "bbmailAutoAuthSuccess", 5);
      appController.registerCommand(19, new AcceptPinChangeCommand("yes"));
      appController.registerViewForward(19, "success", 7);
      appController.registerViewForward(19, "failed", 7);
      appController.registerViewForward(19, "autoAuthSuccess", 48);
      appController.registerCommand(20, new AcceptPinChangeCommand("no"));
      appController.registerViewForward(20, "success", 7);
      appController.registerViewForward(20, "failed", 7);
      appController.registerCommand(21, new DisagreeEndUserAgreementCommand());
      appController.registerViewForward(21, "success", 0);
      appController.registerViewForward(21, "tmobileSuccess", 39);
      appController.registerViewForward(21, "autoAuthSuccess", 39);
      appController.registerCommand(22, new AdvancedEditCommand());
      appController.registerViewForward(22, "success", 7);
      appController.registerViewForward(22, "failedOWA", 35);
      appController.registerViewForward(22, "failed", 36);
      appController.registerViewForward(22, "passwordValidation", 48);
      appController.registerViewForward(22, "validationFailed", 48);
      appController.registerCommand(31, new ValidatePasswordCommand());
      appController.registerViewForward(31, "success", 7);
      appController.registerViewForward(31, "successMore", 48);
      appController.registerViewForward(31, "validationFailed", 48);
      appController.registerCommand(13, new ValidateCommand());
      appController.registerViewForward(13, "success", 48);
      appController.registerCommand(32, new UsernameSetupCommand());
      appController.registerViewForward(32, "success", 48);
      appController.registerViewForward(32, "suggestions", 49);
      appController.registerViewForward(32, "loginFailed", 0);
      appController.registerViewForward(32, "noAccountsToValidate", 7);
      appController.registerViewForward(32, "emailSentConfirmation", 54);
      appController.registerCommand(33, new ValidateSkipCommand());
      appController.registerViewForward(33, "success", 7);
      appController.registerViewForward(33, "successMore", 48);
      appController.registerCommand(34, new ForgotHostedPasswordCommand());
      appController.registerViewForward(34, "success", 7);
      appController.registerViewForward(34, "failed", 50);
      appController.registerViewForward(34, "forwardToScreen", 50);
      appController.registerCommand(35, new AddressBookSetupCommand());
      appController.registerViewForward(35, "success", 56);
      appController.registerCommand(36, new CalendarSetupCommand());
      appController.registerViewForward(36, "synchEnabled", 57);
      appController.registerViewForward(36, "synchNotEnabled", 7);
      return shutdownListeners;
   }
}
