package net.rim.device.api.ui;

public interface UIConstants {
   int UI_CONSTANTS_SHIFT;
   int SPELL_CHECK_RUN;
   int SPELL_CHECK_SHOW_DIALOGS;
   int SPELL_CHECK_HIDE_DIALOGS;
   int SPELL_CHECK_DEFAULT_DIALOGS;
   int SC_BIT_FIELDS_SHIFT;
   int SC_TERMINATION_REASON_MASK;
   int SC_COMPLETED;
   int SC_USER_CANCELLED;
   int SC_ABORTED;
   int SC_USER_INTERACTION_MASK;
   int SC_NO_USER_INTERACTION;
   int SC_USER_INTERACTION;
   int SC_ABORT_REASON_MASK;
   int SC_ABORT_UNKNOWN;
   int SC_ABORT_HOLSTER;
   int SC_ABORT_IDLE;
   int SC_ABORT_RUN_TIME_ERROR;
   int SC_ABORT_SYSTEM_LOCK;
}
