package net.rim.device.api.ui;

public interface UIConstants {
   int UI_CONSTANTS_SHIFT = 8;
   int SPELL_CHECK_RUN = 256;
   int SPELL_CHECK_SHOW_DIALOGS = 512;
   int SPELL_CHECK_HIDE_DIALOGS = 768;
   int SPELL_CHECK_DEFAULT_DIALOGS = 1024;
   int SC_BIT_FIELDS_SHIFT = 16;
   int SC_TERMINATION_REASON_MASK = 3;
   int SC_COMPLETED = 0;
   int SC_USER_CANCELLED = 1;
   int SC_ABORTED = 2;
   int SC_USER_INTERACTION_MASK = 4;
   int SC_NO_USER_INTERACTION = 0;
   int SC_USER_INTERACTION = 4;
   int SC_ABORT_REASON_MASK = 56;
   int SC_ABORT_UNKNOWN = 0;
   int SC_ABORT_HOLSTER = 8;
   int SC_ABORT_IDLE = 16;
   int SC_ABORT_RUN_TIME_ERROR = 24;
   int SC_ABORT_SYSTEM_LOCK = 32;
}
