package net.rim.device.api.system;

public interface DirectConnectListener extends RadioListener {
   int DC_CALL_DISCONNECTED_PLEASE_TRY_AGAIN = 1;
   int DC_CALL_DISCONNECTED_NUMBER_NOT_IN_SERVICE = 2;
   int DC_CALL_DISCONNECTED_PLEASE_TRY_LATER = 3;
   int DC_CALL_DISCONNECTED_SERVICE_CONFLICT = 4;
   int DC_CALL_DISCONNECTED_SYSTEM_BUSY_TRY_LATER = 5;
   int DC_CALL_DISCONNECTED_USER_BUSY_IN_PRIVATE = 6;
   int DC_CALL_DISCONNECTED_USER_BUSY_IN_DATA = 7;
   int DC_CALL_DISCONNECTED_USER_NOT_AUTHORIZED = 8;
   int DC_CALL_DISCONNECTED_USER_NOT_AVAILABLE = 9;
   int DC_CALL_DISCONNECTED_USER_UNKNOWN = 10;
   int DC_CALL_DISCONNECTED_USER_NOT_REACHABLE = 11;
   int DC_CALL_DISCONNECTED_UNKNOWN_REASON = 12;
   int DC_CALL_DISCONNECTED_TARGET_ACKS_ALERT = 14;
   int DC_CALL_DISCONNECTED_USER_CANCELLED = 15;
   int DC_CALL_DISCONNECTED_NORMAL_TERMINATION = 16;
   int DC_REQUEST_FAILED_UNKNOWN = 1;
   int DC_REQUEST_FAILED_INVALID_MODE_INDEX = 2;
   int DC_REQUEST_FAILED_INVALID_AREA_ID = 3;
   int DC_REQUEST_FAILED_SERVICE_INACTIVE = 4;
   int DC_REQUEST_FAILED_SERVICE_ACTIVE = 5;
   int DC_REQUEST_FAILED_OUT_OF_SERVICE = 6;
   int DC_REQUEST_FAILED_ISOLATED_SITE_OPERATION = 7;
   int DC_REQUEST_FAILED_RADIO_LOCKED = 8;
   int DC_REQUEST_FAILED_HIGH_BATTERY_CONDITION = 9;
   int DC_REQUEST_FAILED_HIGH_TEMPERATURE_CONDITION = 10;
   int DC_REQUEST_FAILED_ALREADY_AFFILIATED = 11;
   int DC_REQUEST_FAILED_ALREADY_TRYING_TO_AFFILIATE = 12;
   int DC_REQUEST_FAILED_OUT_OF_DOMAIN = 13;
   int DC_REQUEST_FAILED_INVALID_FLEET_MEMBER_ID = 14;
   int DC_REQUEST_FAILED_NOT_ALLOWED_TO_KEY_ON_SEC_TKGRP = 15;
   int DC_REQUEST_FAILED_RADIO_ALREADY_KEYED = 16;
   int DC_REQUEST_FAILED_RADIO_ALREADY_DEKEYED = 17;
   int DC_REQUEST_FAILED_INVALID_TALKGROUP_ID = 18;
   int DC_CALL_ALERT_STATE_RECEIVED = 1;
   int DC_CALL_ALERT_STATE_SENT = 2;
   int DC_CALL_ALERT_STATE_CLEARED = 3;
   int DC_CALL_ALERT_STATE_STOPPED = 4;
   int DC_TALK_STATUS_CAN_TALK = 1;
   int DC_TALK_STATUS_CANNOT_TALK = 2;
   int DC_TALK_STATUS_PUSH_TO_TALK = 3;

   void dcCallConnected(int var1, int var2, boolean var3);

   void dcCallDisconnected(int var1, int var2, int var3);

   void dcRequestFailed(int var1, int var2, int var3);

   void dcCallStatusUpdated(int var1, int var2);

   void dcTalkStatusUpdated(int var1, int var2, int var3);

   void dcTalkGroupIdUpdated(int var1, boolean var2, int var3);

   void dcCallAlertUpdate(int var1, int var2, int var3);

   void dcServiceUpdated(int var1, boolean var2, boolean var3);
}
