package net.rim.device.api.system;

public interface DirectConnectListener extends RadioListener {
   int DC_CALL_DISCONNECTED_PLEASE_TRY_AGAIN;
   int DC_CALL_DISCONNECTED_NUMBER_NOT_IN_SERVICE;
   int DC_CALL_DISCONNECTED_PLEASE_TRY_LATER;
   int DC_CALL_DISCONNECTED_SERVICE_CONFLICT;
   int DC_CALL_DISCONNECTED_SYSTEM_BUSY_TRY_LATER;
   int DC_CALL_DISCONNECTED_USER_BUSY_IN_PRIVATE;
   int DC_CALL_DISCONNECTED_USER_BUSY_IN_DATA;
   int DC_CALL_DISCONNECTED_USER_NOT_AUTHORIZED;
   int DC_CALL_DISCONNECTED_USER_NOT_AVAILABLE;
   int DC_CALL_DISCONNECTED_USER_UNKNOWN;
   int DC_CALL_DISCONNECTED_USER_NOT_REACHABLE;
   int DC_CALL_DISCONNECTED_UNKNOWN_REASON;
   int DC_CALL_DISCONNECTED_TARGET_ACKS_ALERT;
   int DC_CALL_DISCONNECTED_USER_CANCELLED;
   int DC_CALL_DISCONNECTED_NORMAL_TERMINATION;
   int DC_REQUEST_FAILED_UNKNOWN;
   int DC_REQUEST_FAILED_INVALID_MODE_INDEX;
   int DC_REQUEST_FAILED_INVALID_AREA_ID;
   int DC_REQUEST_FAILED_SERVICE_INACTIVE;
   int DC_REQUEST_FAILED_SERVICE_ACTIVE;
   int DC_REQUEST_FAILED_OUT_OF_SERVICE;
   int DC_REQUEST_FAILED_ISOLATED_SITE_OPERATION;
   int DC_REQUEST_FAILED_RADIO_LOCKED;
   int DC_REQUEST_FAILED_HIGH_BATTERY_CONDITION;
   int DC_REQUEST_FAILED_HIGH_TEMPERATURE_CONDITION;
   int DC_REQUEST_FAILED_ALREADY_AFFILIATED;
   int DC_REQUEST_FAILED_ALREADY_TRYING_TO_AFFILIATE;
   int DC_REQUEST_FAILED_OUT_OF_DOMAIN;
   int DC_REQUEST_FAILED_INVALID_FLEET_MEMBER_ID;
   int DC_REQUEST_FAILED_NOT_ALLOWED_TO_KEY_ON_SEC_TKGRP;
   int DC_REQUEST_FAILED_RADIO_ALREADY_KEYED;
   int DC_REQUEST_FAILED_RADIO_ALREADY_DEKEYED;
   int DC_REQUEST_FAILED_INVALID_TALKGROUP_ID;
   int DC_CALL_ALERT_STATE_RECEIVED;
   int DC_CALL_ALERT_STATE_SENT;
   int DC_CALL_ALERT_STATE_CLEARED;
   int DC_CALL_ALERT_STATE_STOPPED;
   int DC_TALK_STATUS_CAN_TALK;
   int DC_TALK_STATUS_CANNOT_TALK;
   int DC_TALK_STATUS_PUSH_TO_TALK;

   void dcCallConnected(int var1, int var2, boolean var3);

   void dcCallDisconnected(int var1, int var2, int var3);

   void dcRequestFailed(int var1, int var2, int var3);

   void dcCallStatusUpdated(int var1, int var2);

   void dcTalkStatusUpdated(int var1, int var2, int var3);

   void dcTalkGroupIdUpdated(int var1, boolean var2, int var3);

   void dcCallAlertUpdate(int var1, int var2, int var3);

   void dcServiceUpdated(int var1, boolean var2, boolean var3);
}
