package net.rim.device.api.system;

public interface RadioStatusListener extends RadioListener {
   int PDP_STATE_ACTIVE = 0;
   int PDP_STATE_INACTIVE = 1;
   int PDP_STATE_REJECTED = 2;
   int PDP_STATE_IP_ADDRESS_CHANGED = 3;
   int PDP_CAUSE_UNKNOWN = 0;
   int PDP_CAUSE_LLC_FAILURE = 25;
   int PDP_CAUSE_INSUFFICIENT_RESOURCES = 26;
   int PDP_CAUSE_UNKNOWN_APN = 27;
   int PDP_CAUSE_UNKNOWN_PDP = 28;
   int PDP_CAUSE_AUTHENTICATION_FAILED = 29;
   int PDP_CAUSE_REJECTED_BY_GGSN = 30;
   int PDP_CAUSE_REJECTED = 31;
   int PDP_CAUSE_SERVICE_NOT_SUPPORTED = 32;
   int PDP_CAUSE_SERVICE_NOT_SUBSCRIBED = 33;
   int PDP_CAUSE_SERVICE_OUT_OF_ORDER = 34;
   int PDP_CAUSE_NSAPI_ALREADY_USED = 35;
   int PDP_CAUSE_NORMAL_DEACTIVATION = 36;
   int PDP_CAUSE_QOS_NOT_ACCEPTED = 37;
   int PDP_CAUSE_NETWORK_FAILURED = 38;
   int PDP_CAUSE_REACTIVATION_REQUESTED = 39;
   int PDP_CAUSE_NOT_SUPPORTED = 40;
   int PDP_CAUSE_TFT_ALREADY_USED = 41;
   int PDP_CAUSE_TFT_INVALID = 42;
   int PDP_CAUSE_UNKNOWN_PDP_CONTEXT = 43;
   int MM_LOCATION_UPDATE_ACCEPT = 1282;
   int MM_LOCATION_UPDATE_REJECT = 1284;
   int MM_AUTHENTICATION_REQUEST = 1298;
   int MM_AUTHENTICATION_REJECT = 1297;
   int MM_IDENTITY_REQUEST = 1304;
   int MM_TMSI_REALLOC_CMD = 1307;
   int MM_CM_SERVICE_ACCEPT = 1313;
   int MM_CM_SERVICE_REJECT = 1314;
   int MM_MM_STATUS = 1329;
   int MM_ABORT = 1321;
   int MM_MM_INFORMATION = 1330;
   int GMM_ATTACH_ACCEPT = 2050;
   int GMM_ATTACH_REJECT = 2052;
   int GMM_MO_DETACH_ACCEPT = 2054;
   int GMM_RA_UPDATE_ACCEPT = 2057;
   int GMM_MT_DETACH_REQUEST = 2053;
   int GMM_RA_UPDATE_REJECT = 2059;
   int GMM_PTMSI_REALLOC_CMD = 2064;
   int GMM_AUTH_CIPHER_REQUEST = 2066;
   int GMM_AUTH_CIPHER_REJECT = 2068;
   int GMM_IDENTITY_REQUEST = 2069;
   int GMM_GMM_INFORMATION = 2081;
   int SM_PDP_ACTIVATE_ACCEPT = 2626;
   int SM_PDP_ACTIVATE_REJECT = 2627;
   int SM_DEACTIVATE_PDP_REQUEST = 2630;
   int SM_DEACTIVATE_PDP_ACCEPT = 2631;
   int CAUSE_NOT_APPLICABLE = 28672;

   void signalLevel(int var1);

   void networkStarted(int var1, int var2);

   void baseStationChange();

   void radioTurnedOff();

   void pdpStateChange(int var1, int var2, int var3);

   void networkStateChange(int var1);

   void networkScanComplete(boolean var1);

   void networkServiceChange(int var1, int var2);
}
