package net.rim.device.api.system;

public interface SIMCardStatusListener extends SIMCardListener {
   int CARD_INVALID_POWER_OFF;
   int CARD_INVALID_INSERTED_ERROR;
   int CARD_INVALID_REMOVED;
   int CARD_INVALID_INVALID_STATUS_RSP;
   int CARD_INVALID_INITIALISE_FAILED;
   int CARD_INVALID_INVALID_PARAMS;
   int CARD_INVALID_MEMORY_PROBLEM;
   int CARD_INVALID_FILE_NOT_FOUND;
   int CARD_INVALID_SERVICE_NOT_AVAILABLE;
   int CARD_INVALID_GENERAL_FAULT;
   int CARD_INVALID_FILE_INVALIDATED;
   int CARD_INVALID_ALLOC_ERROR;
   int CARD_INVALID_SM_FAULT;
   int CARD_INVALID_CHV1_UNINITIALISED;
   int CARD_INVALID_CHV2_UNINITIALISED;
   int CARD_INVALID_CHV1_UNBLOCK_BLOCKED;
   int CARD_INVALID_CHV2_UNBLOCK_BLOCKED;
   int CARD_INVALID_MEP_CHECK_FAILED;
   int CARD_INVALID_UNKNOWN;
   int CARD_INVALID_CPHS;
   int CARD_INVALID_ERROR_RECOVERY;
   int CARD_INVALID_INVALIDATED;
   int CARD_INVALID_NETWORK_REJECT;
   int CARD_INVALID_MEP_DATA_INVALID;
   int CARD_INVALID_NETWORK_REJECT_NOT_SPECIFIED;
   int CARD_INVALID_NETWORK_REJECT_AUTHENTICATION;
   int CARD_INVALID_NETWORK_REJECT_IMSI;
   int CARD_INVALID_NETWORK_REJECT_MS;
   int CARD_INVALID_NETWORK_REJECT_ME;
   int CARD_FAULT_NORMAL_ENDING;
   int CARD_FAULT_VALID_RES_LENGTH;
   int CARD_FAULT_UPDATE_RETRIES;
   int CARD_FAULT_MEMORY_PROBLEM;
   int CARD_FAULT_NO_EF_SELECTED;
   int CARD_FAULT_INVALID_ADDRESS;
   int CARD_FAULT_FILE_NOT_FOUND;
   int CARD_FAULT_INCONSISTENT_COMMAND;
   int CARD_FAULT_NO_CHV_INITIALISED;
   int CARD_FAULT_ACCESS_DENIED;
   int CARD_FAULT_CHV_STAT_CONTRADICT;
   int CARD_FAULT_INVALID_CONTRADICT;
   int CARD_FAULT_CODE_BLOCKED;
   int CARD_FAULT_MAX_VALUE_REACHED;
   int CARD_FAULT_INCORRECT_P3;
   int CARD_FAULT_INCORRECT_P1_OR_P2;
   int CARD_FAULT_UNKNOWN_INST_CODE;
   int CARD_FAULT_WRONG_INST_CLASS;
   int CARD_FAULT_TECHNICAL_PROBLEM;
   int CARD_FAULT_NORMAL_END_WITH_SIM_INFO;
   int CARD_FAULT_SIMAT_IS_BUSY;
   int CARD_FAULT_DDL_RES_LENGTH;
   int CARD_FAULT_UNKNOWN;

   void cardInserted();

   void cardReady();

   void cardUpdated();

   void cardInvalid(int var1, int var2);

   void cardFault(int var1);

   void smsEFFull();

   void responseDeleteSMS(int var1, int var2);

   void responseMarkSMSAsRead(int var1, int var2);
}
