package net.rim.device.api.system;

public interface SIMCardStatusListener extends SIMCardListener {
   int CARD_INVALID_POWER_OFF = 0;
   int CARD_INVALID_INSERTED_ERROR = 1;
   int CARD_INVALID_REMOVED = 2;
   int CARD_INVALID_INVALID_STATUS_RSP = 3;
   int CARD_INVALID_INITIALISE_FAILED = 4;
   int CARD_INVALID_INVALID_PARAMS = 5;
   int CARD_INVALID_MEMORY_PROBLEM = 6;
   int CARD_INVALID_FILE_NOT_FOUND = 7;
   int CARD_INVALID_SERVICE_NOT_AVAILABLE = 8;
   int CARD_INVALID_GENERAL_FAULT = 9;
   int CARD_INVALID_FILE_INVALIDATED = 10;
   int CARD_INVALID_ALLOC_ERROR = 11;
   int CARD_INVALID_SM_FAULT = 12;
   int CARD_INVALID_CHV1_UNINITIALISED = 13;
   int CARD_INVALID_CHV2_UNINITIALISED = 14;
   int CARD_INVALID_CHV1_UNBLOCK_BLOCKED = 15;
   int CARD_INVALID_CHV2_UNBLOCK_BLOCKED = 16;
   int CARD_INVALID_MEP_CHECK_FAILED = 17;
   int CARD_INVALID_UNKNOWN = 18;
   int CARD_INVALID_CPHS = 19;
   int CARD_INVALID_ERROR_RECOVERY = 20;
   int CARD_INVALID_INVALIDATED = 21;
   int CARD_INVALID_NETWORK_REJECT = 22;
   int CARD_INVALID_MEP_DATA_INVALID = 23;
   int CARD_INVALID_NETWORK_REJECT_NOT_SPECIFIED = 0;
   int CARD_INVALID_NETWORK_REJECT_AUTHENTICATION = 1;
   int CARD_INVALID_NETWORK_REJECT_IMSI = 2;
   int CARD_INVALID_NETWORK_REJECT_MS = 3;
   int CARD_INVALID_NETWORK_REJECT_ME = 6;
   int CARD_FAULT_NORMAL_ENDING = 36864;
   int CARD_FAULT_VALID_RES_LENGTH = 40704;
   int CARD_FAULT_UPDATE_RETRIES = 37376;
   int CARD_FAULT_MEMORY_PROBLEM = 37440;
   int CARD_FAULT_NO_EF_SELECTED = 37888;
   int CARD_FAULT_INVALID_ADDRESS = 37890;
   int CARD_FAULT_FILE_NOT_FOUND = 37892;
   int CARD_FAULT_INCONSISTENT_COMMAND = 37896;
   int CARD_FAULT_NO_CHV_INITIALISED = 38914;
   int CARD_FAULT_ACCESS_DENIED = 38916;
   int CARD_FAULT_CHV_STAT_CONTRADICT = 38920;
   int CARD_FAULT_INVALID_CONTRADICT = 38928;
   int CARD_FAULT_CODE_BLOCKED = 38976;
   int CARD_FAULT_MAX_VALUE_REACHED = 38992;
   int CARD_FAULT_INCORRECT_P3 = 26368;
   int CARD_FAULT_INCORRECT_P1_OR_P2 = 27392;
   int CARD_FAULT_UNKNOWN_INST_CODE = 27904;
   int CARD_FAULT_WRONG_INST_CLASS = 28160;
   int CARD_FAULT_TECHNICAL_PROBLEM = 28416;
   int CARD_FAULT_NORMAL_END_WITH_SIM_INFO = 37120;
   int CARD_FAULT_SIMAT_IS_BUSY = 37632;
   int CARD_FAULT_DDL_RES_LENGTH = 40448;
   int CARD_FAULT_UNKNOWN = 0;

   void cardInserted();

   void cardReady();

   void cardUpdated();

   void cardInvalid(int var1, int var2);

   void cardFault(int var1);

   void smsEFFull();

   void responseDeleteSMS(int var1, int var2);

   void responseMarkSMSAsRead(int var1, int var2);
}
